// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: crashpilot/interface/cp_interface.proto
// Protobuf C++ Version: 7.34.1

#ifndef crashpilot_2finterface_2fcp_5finterface_2eproto_2epb_2eh
#define crashpilot_2finterface_2fcp_5finterface_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "crashpilot/cp_robot/cp_cp_robot.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_crashpilot_2finterface_2fcp_5finterface_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_crashpilot_2finterface_2fcp_5finterface_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_crashpilot_2finterface_2fcp_5finterface_2eproto;
}  // extern "C"
class CP_Interface;
struct CP_InterfaceDefaultTypeInternal;
extern CP_InterfaceDefaultTypeInternal _CP_Interface_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CP_Interface_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CP_Interface final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CP_Interface) */ {
 public:
  inline CP_Interface() : CP_Interface(nullptr) {}
  ~CP_Interface() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CP_Interface* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CP_Interface));
  }
#endif

  template <typename = void>
  explicit constexpr CP_Interface(::google::protobuf::internal::ConstantInitialized);

  inline CP_Interface(const CP_Interface& from) : CP_Interface(nullptr, from) {}
  inline CP_Interface(CP_Interface&& from) noexcept
      : CP_Interface(nullptr, ::std::move(from)) {}
  inline CP_Interface& operator=(const CP_Interface& from) {
    CopyFrom(from);
    return *this;
  }
  inline CP_Interface& operator=(CP_Interface&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const CP_Interface& default_instance() {
    return *reinterpret_cast<const CP_Interface*>(
        &_CP_Interface_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CP_Interface& a, CP_Interface& b) { a.Swap(&b); }
  inline void Swap(CP_Interface* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CP_Interface* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CP_Interface* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CP_Interface>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CP_Interface& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CP_Interface& from) { CP_Interface::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CP_Interface* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CP_Interface"; }

  explicit CP_Interface(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CP_Interface(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CP_Interface& from);
  CP_Interface(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CP_Interface&& from) noexcept
      : CP_Interface(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandFieldNumber = 2,
    kRobotIdFieldNumber = 1,
  };
  // required .CP_Command command = 2 [json_name = "command"];
  [[nodiscard]] bool has_command()
      const;
  void clear_command() ;
  [[nodiscard]] const ::CP_Command& command() const;
  [[nodiscard]] ::CP_Command* PROTOBUF_NULLABLE release_command();
  ::CP_Command* PROTOBUF_NONNULL mutable_command();
  void set_allocated_command(::CP_Command* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_command(::CP_Command* PROTOBUF_NULLABLE value);
  ::CP_Command* PROTOBUF_NULLABLE unsafe_arena_release_command();

  private:
  const ::CP_Command& _internal_command() const;
  ::CP_Command* PROTOBUF_NONNULL _internal_mutable_command();

  public:
  // required uint32 robot_id = 1 [json_name = "robotId"];
  [[nodiscard]] bool has_robot_id()
      const;
  void clear_robot_id() ;
  [[nodiscard]] ::uint32_t robot_id() const;
  void set_robot_id(::uint32_t value);

  private:
  ::uint32_t _internal_robot_id() const;
  void _internal_set_robot_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CP_Interface)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CP_Interface& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::CP_Command* PROTOBUF_NULLABLE command_;
    ::uint32_t robot_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_crashpilot_2finterface_2fcp_5finterface_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CP_Interface_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CP_Interface

// required uint32 robot_id = 1 [json_name = "robotId"];
inline bool CP_Interface::has_robot_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CP_Interface::clear_robot_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CP_Interface::robot_id() const {
  // @@protoc_insertion_point(field_get:CP_Interface.robot_id)
  return _internal_robot_id();
}
inline void CP_Interface::set_robot_id(::uint32_t value) {
  _internal_set_robot_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CP_Interface.robot_id)
}
inline ::uint32_t CP_Interface::_internal_robot_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.robot_id_;
}
inline void CP_Interface::_internal_set_robot_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_id_ = value;
}

// required .CP_Command command = 2 [json_name = "command"];
inline bool CP_Interface::has_command() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.command_ != nullptr);
  return value;
}
inline const ::CP_Command& CP_Interface::_internal_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::CP_Command* p = _impl_.command_;
  return p != nullptr ? *p : reinterpret_cast<const ::CP_Command&>(::_CP_Command_default_instance_);
}
inline const ::CP_Command& CP_Interface::command() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CP_Interface.command)
  return _internal_command();
}
inline void CP_Interface::unsafe_arena_set_allocated_command(
    ::CP_Command* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.command_);
  }
  _impl_.command_ = reinterpret_cast<::CP_Command*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CP_Interface.command)
}
inline ::CP_Command* PROTOBUF_NULLABLE CP_Interface::release_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::CP_Command* released = _impl_.command_;
  _impl_.command_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::CP_Command* PROTOBUF_NULLABLE CP_Interface::unsafe_arena_release_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CP_Interface.command)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::CP_Command* temp = _impl_.command_;
  _impl_.command_ = nullptr;
  return temp;
}
inline ::CP_Command* PROTOBUF_NONNULL CP_Interface::_internal_mutable_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.command_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::CP_Command>(GetArena());
    _impl_.command_ = reinterpret_cast<::CP_Command*>(p);
  }
  return _impl_.command_;
}
inline ::CP_Command* PROTOBUF_NONNULL CP_Interface::mutable_command()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::CP_Command* _msg = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:CP_Interface.command)
  return _msg;
}
inline void CP_Interface::set_allocated_command(::CP_Command* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.command_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.command_ = reinterpret_cast<::CP_Command*>(value);
  // @@protoc_insertion_point(field_set_allocated:CP_Interface.command)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // crashpilot_2finterface_2fcp_5finterface_2eproto_2epb_2eh
