[package]
name = "crashpilot"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.50.0", features = ["net", "sync", "rt", "rt-multi-thread", "macros", "time", "io-util"] }
serde = { version = "1.0.228", features = ["derive"] }
core_dump = { git = "https://github.com/Technulgy-LGNU/core-dump", features = ["serde"]}
toml = "1.1.2+spec-1.1.0"
anyhow = "1.0.103"

[build-dependencies]

[features]
default = []