// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vision_tracked/messages_robocup_ssl_wrapper_legacy.proto
// Protobuf C++ Version: 7.34.1

#ifndef vision_5ftracked_2fmessages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto_2epb_2eh
#define vision_5ftracked_2fmessages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "vision_tracked/messages_robocup_ssl_detection.pb.h"
#include "vision_tracked/messages_robocup_ssl_geometry_legacy.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_vision_5ftracked_2fmessages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_vision_5ftracked_2fmessages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_vision_5ftracked_2fmessages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto;
}  // extern "C"
namespace RoboCup2014Legacy {
namespace Wrapper {
class SSL_WrapperPacket;
struct SSL_WrapperPacketDefaultTypeInternal;
extern SSL_WrapperPacketDefaultTypeInternal _SSL_WrapperPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SSL_WrapperPacket_class_data_;
}  // namespace Wrapper
}  // namespace RoboCup2014Legacy
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace RoboCup2014Legacy {
namespace Wrapper {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SSL_WrapperPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket) */ {
 public:
  inline SSL_WrapperPacket() : SSL_WrapperPacket(nullptr) {}
  ~SSL_WrapperPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SSL_WrapperPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SSL_WrapperPacket));
  }
#endif

  template <typename = void>
  explicit constexpr SSL_WrapperPacket(::google::protobuf::internal::ConstantInitialized);

  inline SSL_WrapperPacket(const SSL_WrapperPacket& from) : SSL_WrapperPacket(nullptr, from) {}
  inline SSL_WrapperPacket(SSL_WrapperPacket&& from) noexcept
      : SSL_WrapperPacket(nullptr, ::std::move(from)) {}
  inline SSL_WrapperPacket& operator=(const SSL_WrapperPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSL_WrapperPacket& operator=(SSL_WrapperPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const SSL_WrapperPacket& default_instance() {
    return *reinterpret_cast<const SSL_WrapperPacket*>(
        &_SSL_WrapperPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SSL_WrapperPacket& a, SSL_WrapperPacket& b) { a.Swap(&b); }
  inline void Swap(SSL_WrapperPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSL_WrapperPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SSL_WrapperPacket* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SSL_WrapperPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SSL_WrapperPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SSL_WrapperPacket& from) { SSL_WrapperPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SSL_WrapperPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RoboCup2014Legacy.Wrapper.SSL_WrapperPacket"; }

  explicit SSL_WrapperPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SSL_WrapperPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SSL_WrapperPacket& from);
  SSL_WrapperPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SSL_WrapperPacket&& from) noexcept
      : SSL_WrapperPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDetectionFieldNumber = 1,
    kGeometryFieldNumber = 2,
  };
  // optional .SSL_DetectionFrame detection = 1 [json_name = "detection"];
  [[nodiscard]] bool has_detection()
      const;
  void clear_detection() ;
  [[nodiscard]] const ::SSL_DetectionFrame& detection() const;
  [[nodiscard]] ::SSL_DetectionFrame* PROTOBUF_NULLABLE release_detection();
  ::SSL_DetectionFrame* PROTOBUF_NONNULL mutable_detection();
  void set_allocated_detection(::SSL_DetectionFrame* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_detection(::SSL_DetectionFrame* PROTOBUF_NULLABLE value);
  ::SSL_DetectionFrame* PROTOBUF_NULLABLE unsafe_arena_release_detection();

  private:
  const ::SSL_DetectionFrame& _internal_detection() const;
  ::SSL_DetectionFrame* PROTOBUF_NONNULL _internal_mutable_detection();

  public:
  // optional .RoboCup2014Legacy.Geometry.SSL_GeometryData geometry = 2 [json_name = "geometry"];
  [[nodiscard]] bool has_geometry()
      const;
  void clear_geometry() ;
  [[nodiscard]] const ::RoboCup2014Legacy::Geometry::SSL_GeometryData& geometry() const;
  [[nodiscard]] ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE release_geometry();
  ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NONNULL mutable_geometry();
  void set_allocated_geometry(::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_geometry(::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE value);
  ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE unsafe_arena_release_geometry();

  private:
  const ::RoboCup2014Legacy::Geometry::SSL_GeometryData& _internal_geometry() const;
  ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NONNULL _internal_mutable_geometry();

  public:
  // @@protoc_insertion_point(class_scope:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SSL_WrapperPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::SSL_DetectionFrame* PROTOBUF_NULLABLE detection_;
    ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE geometry_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vision_5ftracked_2fmessages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SSL_WrapperPacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SSL_WrapperPacket

// optional .SSL_DetectionFrame detection = 1 [json_name = "detection"];
inline bool SSL_WrapperPacket::has_detection() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.detection_ != nullptr);
  return value;
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::_internal_detection() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::SSL_DetectionFrame* p = _impl_.detection_;
  return p != nullptr ? *p : reinterpret_cast<const ::SSL_DetectionFrame&>(::_SSL_DetectionFrame_default_instance_);
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::detection() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
  return _internal_detection();
}
inline void SSL_WrapperPacket::unsafe_arena_set_allocated_detection(
    ::SSL_DetectionFrame* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.detection_);
  }
  _impl_.detection_ = reinterpret_cast<::SSL_DetectionFrame*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
}
inline ::SSL_DetectionFrame* PROTOBUF_NULLABLE SSL_WrapperPacket::release_detection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::SSL_DetectionFrame* released = _impl_.detection_;
  _impl_.detection_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::SSL_DetectionFrame* PROTOBUF_NULLABLE SSL_WrapperPacket::unsafe_arena_release_detection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::SSL_DetectionFrame* temp = _impl_.detection_;
  _impl_.detection_ = nullptr;
  return temp;
}
inline ::SSL_DetectionFrame* PROTOBUF_NONNULL SSL_WrapperPacket::_internal_mutable_detection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.detection_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::SSL_DetectionFrame>(GetArena());
    _impl_.detection_ = reinterpret_cast<::SSL_DetectionFrame*>(p);
  }
  return _impl_.detection_;
}
inline ::SSL_DetectionFrame* PROTOBUF_NONNULL SSL_WrapperPacket::mutable_detection()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::SSL_DetectionFrame* _msg = _internal_mutable_detection();
  // @@protoc_insertion_point(field_mutable:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
  return _msg;
}
inline void SSL_WrapperPacket::set_allocated_detection(::SSL_DetectionFrame* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.detection_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.detection_ = reinterpret_cast<::SSL_DetectionFrame*>(value);
  // @@protoc_insertion_point(field_set_allocated:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.detection)
}

// optional .RoboCup2014Legacy.Geometry.SSL_GeometryData geometry = 2 [json_name = "geometry"];
inline bool SSL_WrapperPacket::has_geometry() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.geometry_ != nullptr);
  return value;
}
inline const ::RoboCup2014Legacy::Geometry::SSL_GeometryData& SSL_WrapperPacket::_internal_geometry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::RoboCup2014Legacy::Geometry::SSL_GeometryData* p = _impl_.geometry_;
  return p != nullptr ? *p : reinterpret_cast<const ::RoboCup2014Legacy::Geometry::SSL_GeometryData&>(::RoboCup2014Legacy::Geometry::_SSL_GeometryData_default_instance_);
}
inline const ::RoboCup2014Legacy::Geometry::SSL_GeometryData& SSL_WrapperPacket::geometry() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
  return _internal_geometry();
}
inline void SSL_WrapperPacket::unsafe_arena_set_allocated_geometry(
    ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.geometry_);
  }
  _impl_.geometry_ = reinterpret_cast<::RoboCup2014Legacy::Geometry::SSL_GeometryData*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
}
inline ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE SSL_WrapperPacket::release_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::RoboCup2014Legacy::Geometry::SSL_GeometryData* released = _impl_.geometry_;
  _impl_.geometry_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE SSL_WrapperPacket::unsafe_arena_release_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::RoboCup2014Legacy::Geometry::SSL_GeometryData* temp = _impl_.geometry_;
  _impl_.geometry_ = nullptr;
  return temp;
}
inline ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NONNULL SSL_WrapperPacket::_internal_mutable_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.geometry_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::RoboCup2014Legacy::Geometry::SSL_GeometryData>(GetArena());
    _impl_.geometry_ = reinterpret_cast<::RoboCup2014Legacy::Geometry::SSL_GeometryData*>(p);
  }
  return _impl_.geometry_;
}
inline ::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NONNULL SSL_WrapperPacket::mutable_geometry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::RoboCup2014Legacy::Geometry::SSL_GeometryData* _msg = _internal_mutable_geometry();
  // @@protoc_insertion_point(field_mutable:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
  return _msg;
}
inline void SSL_WrapperPacket::set_allocated_geometry(::RoboCup2014Legacy::Geometry::SSL_GeometryData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.geometry_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.geometry_ = reinterpret_cast<::RoboCup2014Legacy::Geometry::SSL_GeometryData*>(value);
  // @@protoc_insertion_point(field_set_allocated:RoboCup2014Legacy.Wrapper.SSL_WrapperPacket.geometry)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Wrapper
}  // namespace RoboCup2014Legacy


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // vision_5ftracked_2fmessages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto_2epb_2eh
