# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision_tracked/messages_robocup_ssl_geometry_legacy.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'vision_tracked/messages_robocup_ssl_geometry_legacy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vision_tracked import messages_robocup_ssl_geometry_pb2 as vision__tracked_dot_messages__robocup__ssl__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9vision_tracked/messages_robocup_ssl_geometry_legacy.proto\x12\x1aRoboCup2014Legacy.Geometry\x1a\x32vision_tracked/messages_robocup_ssl_geometry.proto\"\xf3\x04\n\x15SSL_GeometryFieldSize\x12\x1d\n\nline_width\x18\x01 \x02(\x05R\tlineWidth\x12!\n\x0c\x66ield_length\x18\x02 \x02(\x05R\x0b\x66ieldLength\x12\x1f\n\x0b\x66ield_width\x18\x03 \x02(\x05R\nfieldWidth\x12%\n\x0e\x62oundary_width\x18\x04 \x02(\x05R\rboundaryWidth\x12#\n\rreferee_width\x18\x05 \x02(\x05R\x0crefereeWidth\x12\x1d\n\ngoal_width\x18\x06 \x02(\x05R\tgoalWidth\x12\x1d\n\ngoal_depth\x18\x07 \x02(\x05R\tgoalDepth\x12&\n\x0fgoal_wall_width\x18\x08 \x02(\x05R\rgoalWallWidth\x12\x30\n\x14\x63\x65nter_circle_radius\x18\t \x02(\x05R\x12\x63\x65nterCircleRadius\x12%\n\x0e\x64\x65\x66\x65nse_radius\x18\n \x02(\x05R\rdefenseRadius\x12\'\n\x0f\x64\x65\x66\x65nse_stretch\x18\x0b \x02(\x05R\x0e\x64\x65\x66\x65nseStretch\x12<\n\x1b\x66ree_kick_from_defense_dist\x18\x0c \x02(\x05R\x17\x66reeKickFromDefenseDist\x12G\n!penalty_spot_from_field_line_dist\x18\r \x02(\x05R\x1cpenaltySpotFromFieldLineDist\x12<\n\x1bpenalty_line_from_spot_dist\x18\x0e \x02(\x05R\x17penaltyLineFromSpotDist\"\x91\x01\n\x10SSL_GeometryData\x12G\n\x05\x66ield\x18\x01 \x02(\x0b\x32\x31.RoboCup2014Legacy.Geometry.SSL_GeometryFieldSizeR\x05\x66ield\x12\x34\n\x05\x63\x61lib\x18\x02 \x03(\x0b\x32\x1e.SSL_GeometryCameraCalibrationR\x05\x63\x61libB\xd0\x01\n\x1e\x63om.RoboCup2014Legacy.GeometryB%MessagesRobocupSslGeometryLegacyProtoP\x01\xa2\x02\x03RGX\xaa\x02\x1aRoboCup2014Legacy.Geometry\xca\x02\x1aRoboCup2014Legacy\\Geometry\xe2\x02&RoboCup2014Legacy\\Geometry\\GPBMetadata\xea\x02\x1bRoboCup2014Legacy::Geometry')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_tracked.messages_robocup_ssl_geometry_legacy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.RoboCup2014Legacy.GeometryB%MessagesRobocupSslGeometryLegacyProtoP\001\242\002\003RGX\252\002\032RoboCup2014Legacy.Geometry\312\002\032RoboCup2014Legacy\\Geometry\342\002&RoboCup2014Legacy\\Geometry\\GPBMetadata\352\002\033RoboCup2014Legacy::Geometry'
  _globals['_SSL_GEOMETRYFIELDSIZE']._serialized_start=142
  _globals['_SSL_GEOMETRYFIELDSIZE']._serialized_end=769
  _globals['_SSL_GEOMETRYDATA']._serialized_start=772
  _globals['_SSL_GEOMETRYDATA']._serialized_end=917
# @@protoc_insertion_point(module_scope)
