// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: engine/ssl_gc_engine_config.proto
// Protobuf C++ Version: 7.34.1

#ifndef engine_2fssl_5fgc_5fengine_5fconfig_2eproto_2epb_2eh
#define engine_2fssl_5fgc_5fengine_5fconfig_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_engine_2fssl_5fgc_5fengine_5fconfig_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_engine_2fssl_5fgc_5fengine_5fconfig_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_engine_2fssl_5fgc_5fengine_5fconfig_2eproto;
}  // extern "C"
enum AutoRefConfig_Behavior : int;
extern const uint32_t AutoRefConfig_Behavior_internal_data_[];
enum Config_Behavior : int;
extern const uint32_t Config_Behavior_internal_data_[];
class AutoRefConfig;
struct AutoRefConfigDefaultTypeInternal;
extern AutoRefConfigDefaultTypeInternal _AutoRefConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AutoRefConfig_class_data_;
class AutoRefConfig_GameEventBehaviorEntry_DoNotUse;
struct AutoRefConfig_GameEventBehaviorEntry_DoNotUseDefaultTypeInternal;
extern AutoRefConfig_GameEventBehaviorEntry_DoNotUseDefaultTypeInternal _AutoRefConfig_GameEventBehaviorEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AutoRefConfig_GameEventBehaviorEntry_DoNotUse_class_data_;
class Config;
struct ConfigDefaultTypeInternal;
extern ConfigDefaultTypeInternal _Config_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Config_class_data_;
class Config_AutoRefConfigsEntry_DoNotUse;
struct Config_AutoRefConfigsEntry_DoNotUseDefaultTypeInternal;
extern Config_AutoRefConfigsEntry_DoNotUseDefaultTypeInternal _Config_AutoRefConfigsEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Config_AutoRefConfigsEntry_DoNotUse_class_data_;
class Config_GameEventBehaviorEntry_DoNotUse;
struct Config_GameEventBehaviorEntry_DoNotUseDefaultTypeInternal;
extern Config_GameEventBehaviorEntry_DoNotUseDefaultTypeInternal _Config_GameEventBehaviorEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Config_GameEventBehaviorEntry_DoNotUse_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::AutoRefConfig_Behavior_internal_data_>
    internal::EnumTraitsImpl::value<::AutoRefConfig_Behavior>;
template <>
internal::EnumTraitsT<::Config_Behavior_internal_data_>
    internal::EnumTraitsImpl::value<::Config_Behavior>;
}  // namespace protobuf
}  // namespace google

enum Config_Behavior : int {
  Config_Behavior_BEHAVIOR_UNKNOWN = 0,
  Config_Behavior_BEHAVIOR_ACCEPT = 1,
  Config_Behavior_BEHAVIOR_ACCEPT_MAJORITY = 2,
  Config_Behavior_BEHAVIOR_PROPOSE_ONLY = 3,
  Config_Behavior_BEHAVIOR_LOG = 4,
  Config_Behavior_BEHAVIOR_IGNORE = 5,
};

extern const uint32_t Config_Behavior_internal_data_[];
inline constexpr Config_Behavior Config_Behavior_Behavior_MIN =
    static_cast<Config_Behavior>(0);
inline constexpr Config_Behavior Config_Behavior_Behavior_MAX =
    static_cast<Config_Behavior>(5);
[[nodiscard]] inline bool Config_Behavior_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int Config_Behavior_Behavior_ARRAYSIZE = 5 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
Config_Behavior_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(Config_Behavior) {
  return Config_Behavior_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& Config_Behavior_Name(T value) {
  static_assert(::std::is_same<T, Config_Behavior>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Behavior_Name().");
  return Config_Behavior_Name(static_cast<Config_Behavior>(value));
}
template <>
[[nodiscard]] inline const ::std::string& Config_Behavior_Name(Config_Behavior value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Config_Behavior_descriptor, 0, 5>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool Config_Behavior_Parse(
    ::absl::string_view name, Config_Behavior* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Config_Behavior>(Config_Behavior_descriptor(), name,
                                           value);
}
enum AutoRefConfig_Behavior : int {
  AutoRefConfig_Behavior_BEHAVIOR_UNKNOWN = 0,
  AutoRefConfig_Behavior_BEHAVIOR_ACCEPT = 1,
  AutoRefConfig_Behavior_BEHAVIOR_LOG = 2,
  AutoRefConfig_Behavior_BEHAVIOR_IGNORE = 3,
};

extern const uint32_t AutoRefConfig_Behavior_internal_data_[];
inline constexpr AutoRefConfig_Behavior AutoRefConfig_Behavior_Behavior_MIN =
    static_cast<AutoRefConfig_Behavior>(0);
inline constexpr AutoRefConfig_Behavior AutoRefConfig_Behavior_Behavior_MAX =
    static_cast<AutoRefConfig_Behavior>(3);
[[nodiscard]] inline bool AutoRefConfig_Behavior_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int AutoRefConfig_Behavior_Behavior_ARRAYSIZE = 3 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
AutoRefConfig_Behavior_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(AutoRefConfig_Behavior) {
  return AutoRefConfig_Behavior_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& AutoRefConfig_Behavior_Name(T value) {
  static_assert(::std::is_same<T, AutoRefConfig_Behavior>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Behavior_Name().");
  return AutoRefConfig_Behavior_Name(static_cast<AutoRefConfig_Behavior>(value));
}
template <>
[[nodiscard]] inline const ::std::string& AutoRefConfig_Behavior_Name(AutoRefConfig_Behavior value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AutoRefConfig_Behavior_descriptor, 0, 3>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool AutoRefConfig_Behavior_Parse(
    ::absl::string_view name, AutoRefConfig_Behavior* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<AutoRefConfig_Behavior>(AutoRefConfig_Behavior_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Config_GameEventBehaviorEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::Config_Behavior,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_ENUM> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::Config_Behavior,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>;
  Config_GameEventBehaviorEntry_DoNotUse();
  template <typename = void>
  explicit constexpr Config_GameEventBehaviorEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit Config_GameEventBehaviorEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_Config_GameEventBehaviorEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_engine_2fssl_5fgc_5fengine_5fconfig_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull Config_GameEventBehaviorEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AutoRefConfig_GameEventBehaviorEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::AutoRefConfig_Behavior,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_ENUM> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::AutoRefConfig_Behavior,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>;
  AutoRefConfig_GameEventBehaviorEntry_DoNotUse();
  template <typename = void>
  explicit constexpr AutoRefConfig_GameEventBehaviorEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit AutoRefConfig_GameEventBehaviorEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_AutoRefConfig_GameEventBehaviorEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_engine_2fssl_5fgc_5fengine_5fconfig_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull AutoRefConfig_GameEventBehaviorEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AutoRefConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AutoRefConfig) */ {
 public:
  inline AutoRefConfig() : AutoRefConfig(nullptr) {}
  ~AutoRefConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AutoRefConfig* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AutoRefConfig));
  }
#endif

  template <typename = void>
  explicit constexpr AutoRefConfig(::google::protobuf::internal::ConstantInitialized);

  inline AutoRefConfig(const AutoRefConfig& from) : AutoRefConfig(nullptr, from) {}
  inline AutoRefConfig(AutoRefConfig&& from) noexcept
      : AutoRefConfig(nullptr, ::std::move(from)) {}
  inline AutoRefConfig& operator=(const AutoRefConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutoRefConfig& operator=(AutoRefConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AutoRefConfig& default_instance() {
    return *reinterpret_cast<const AutoRefConfig*>(
        &_AutoRefConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(AutoRefConfig& a, AutoRefConfig& b) { a.Swap(&b); }
  inline void Swap(AutoRefConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutoRefConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AutoRefConfig* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AutoRefConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutoRefConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutoRefConfig& from) { AutoRefConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AutoRefConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AutoRefConfig"; }

  explicit AutoRefConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AutoRefConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AutoRefConfig& from);
  AutoRefConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AutoRefConfig&& from) noexcept
      : AutoRefConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Behavior = AutoRefConfig_Behavior;
  static constexpr Behavior BEHAVIOR_UNKNOWN = AutoRefConfig_Behavior_BEHAVIOR_UNKNOWN;
  static constexpr Behavior BEHAVIOR_ACCEPT = AutoRefConfig_Behavior_BEHAVIOR_ACCEPT;
  static constexpr Behavior BEHAVIOR_LOG = AutoRefConfig_Behavior_BEHAVIOR_LOG;
  static constexpr Behavior BEHAVIOR_IGNORE = AutoRefConfig_Behavior_BEHAVIOR_IGNORE;
  [[nodiscard]] static inline bool Behavior_IsValid(int value) {
    return AutoRefConfig_Behavior_IsValid(value);
  }
  static constexpr Behavior Behavior_MIN = AutoRefConfig_Behavior_Behavior_MIN;
  static constexpr Behavior Behavior_MAX = AutoRefConfig_Behavior_Behavior_MAX;
  static constexpr int Behavior_ARRAYSIZE = AutoRefConfig_Behavior_Behavior_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Behavior_descriptor() {
    return AutoRefConfig_Behavior_descriptor();
  }
  template <typename T>
  [[nodiscard]] static inline const ::std::string& Behavior_Name(T value) {
    return AutoRefConfig_Behavior_Name(value);
  }
  [[nodiscard]] static inline bool Behavior_Parse(
      ::absl::string_view name, Behavior* PROTOBUF_NONNULL value) {
    return AutoRefConfig_Behavior_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kGameEventBehaviorFieldNumber = 1,
  };
  // map<string, .AutoRefConfig.Behavior> game_event_behavior = 1 [json_name = "gameEventBehavior"];
  [[nodiscard]] int game_event_behavior_size()
      const;
  private:
  int _internal_game_event_behavior_size() const;

  public:
  void clear_game_event_behavior() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>& game_event_behavior() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>* PROTOBUF_NONNULL mutable_game_event_behavior();

  private:
  const ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>& _internal_game_event_behavior() const;
  ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>* PROTOBUF_NONNULL _internal_mutable_game_event_behavior();

  public:
  // @@protoc_insertion_point(class_scope:AutoRefConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AutoRefConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<AutoRefConfig_GameEventBehaviorEntry_DoNotUse, ::std::string, ::AutoRefConfig_Behavior> game_event_behavior_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_engine_2fssl_5fgc_5fengine_5fconfig_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AutoRefConfig_class_data_;
// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Config_AutoRefConfigsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  Config_AutoRefConfigsEntry_DoNotUse();
  template <typename = void>
  explicit constexpr Config_AutoRefConfigsEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit Config_AutoRefConfigsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_Config_AutoRefConfigsEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_engine_2fssl_5fgc_5fengine_5fconfig_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull Config_AutoRefConfigsEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Config final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Config) */ {
 public:
  inline Config() : Config(nullptr) {}
  ~Config() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Config* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Config));
  }
#endif

  template <typename = void>
  explicit constexpr Config(::google::protobuf::internal::ConstantInitialized);

  inline Config(const Config& from) : Config(nullptr, from) {}
  inline Config(Config&& from) noexcept
      : Config(nullptr, ::std::move(from)) {}
  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }
  inline Config& operator=(Config&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Config& default_instance() {
    return *reinterpret_cast<const Config*>(
        &_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Config& a, Config& b) { a.Swap(&b); }
  inline void Swap(Config* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Config* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Config* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Config>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Config& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Config& from) { Config::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Config* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Config"; }

  explicit Config(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Config(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Config& from);
  Config(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Config&& from) noexcept
      : Config(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Behavior = Config_Behavior;
  static constexpr Behavior BEHAVIOR_UNKNOWN = Config_Behavior_BEHAVIOR_UNKNOWN;
  static constexpr Behavior BEHAVIOR_ACCEPT = Config_Behavior_BEHAVIOR_ACCEPT;
  static constexpr Behavior BEHAVIOR_ACCEPT_MAJORITY = Config_Behavior_BEHAVIOR_ACCEPT_MAJORITY;
  static constexpr Behavior BEHAVIOR_PROPOSE_ONLY = Config_Behavior_BEHAVIOR_PROPOSE_ONLY;
  static constexpr Behavior BEHAVIOR_LOG = Config_Behavior_BEHAVIOR_LOG;
  static constexpr Behavior BEHAVIOR_IGNORE = Config_Behavior_BEHAVIOR_IGNORE;
  [[nodiscard]] static inline bool Behavior_IsValid(int value) {
    return Config_Behavior_IsValid(value);
  }
  static constexpr Behavior Behavior_MIN = Config_Behavior_Behavior_MIN;
  static constexpr Behavior Behavior_MAX = Config_Behavior_Behavior_MAX;
  static constexpr int Behavior_ARRAYSIZE = Config_Behavior_Behavior_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Behavior_descriptor() {
    return Config_Behavior_descriptor();
  }
  template <typename T>
  [[nodiscard]] static inline const ::std::string& Behavior_Name(T value) {
    return Config_Behavior_Name(value);
  }
  [[nodiscard]] static inline bool Behavior_Parse(
      ::absl::string_view name, Behavior* PROTOBUF_NONNULL value) {
    return Config_Behavior_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTeamsFieldNumber = 4,
    kActiveTrackerSourceFieldNumber = 3,
    kAutoContinueFieldNumber = 5,
    kGameEventBehaviorFieldNumber = 1,
    kAutoRefConfigsFieldNumber = 2,
  };
  // repeated string teams = 4 [json_name = "teams"];
  [[nodiscard]] int teams_size()
      const;
  private:
  int _internal_teams_size() const;

  public:
  void clear_teams() ;
  [[nodiscard]] const ::std::string& teams(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_teams(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_teams(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_teams();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_teams(Arg_&& value, Args_... args);
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::std::string>&
  teams() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
  mutable_teams();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_teams() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_teams();

  public:
  // optional string active_tracker_source = 3 [json_name = "activeTrackerSource"];
  [[nodiscard]] bool has_active_tracker_source()
      const;
  void clear_active_tracker_source() ;
  [[nodiscard]] const ::std::string& active_tracker_source() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_active_tracker_source(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_active_tracker_source();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_active_tracker_source();
  void set_allocated_active_tracker_source(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_active_tracker_source() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_active_tracker_source(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_active_tracker_source();

  public:
  // optional bool auto_continue = 5 [json_name = "autoContinue"];
  [[nodiscard]] bool has_auto_continue()
      const;
  void clear_auto_continue() ;
  [[nodiscard]] bool auto_continue() const;
  void set_auto_continue(bool value);

  private:
  bool _internal_auto_continue() const;
  void _internal_set_auto_continue(bool value);

  public:
  // map<string, .Config.Behavior> game_event_behavior = 1 [json_name = "gameEventBehavior"];
  [[nodiscard]] int game_event_behavior_size()
      const;
  private:
  int _internal_game_event_behavior_size() const;

  public:
  void clear_game_event_behavior() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::Config_Behavior>& game_event_behavior() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::Config_Behavior>* PROTOBUF_NONNULL mutable_game_event_behavior();

  private:
  const ::google::protobuf::Map<::std::string, ::Config_Behavior>& _internal_game_event_behavior() const;
  ::google::protobuf::Map<::std::string, ::Config_Behavior>* PROTOBUF_NONNULL _internal_mutable_game_event_behavior();

  public:
  // map<string, .AutoRefConfig> auto_ref_configs = 2 [json_name = "autoRefConfigs"];
  [[nodiscard]] int auto_ref_configs_size()
      const;
  private:
  int _internal_auto_ref_configs_size() const;

  public:
  void clear_auto_ref_configs() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::AutoRefConfig>& auto_ref_configs() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::AutoRefConfig>* PROTOBUF_NONNULL mutable_auto_ref_configs();

  private:
  const ::google::protobuf::Map<::std::string, ::AutoRefConfig>& _internal_auto_ref_configs() const;
  ::google::protobuf::Map<::std::string, ::AutoRefConfig>* PROTOBUF_NONNULL _internal_mutable_auto_ref_configs();

  public:
  // @@protoc_insertion_point(class_scope:Config)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 5,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Config& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> teams_;
    ::google::protobuf::internal::ArenaStringPtr active_tracker_source_;
    bool auto_continue_;
    ::google::protobuf::internal::MapField<Config_GameEventBehaviorEntry_DoNotUse, ::std::string, ::Config_Behavior> game_event_behavior_;
    ::google::protobuf::internal::MapField<Config_AutoRefConfigsEntry_DoNotUse, ::std::string, ::AutoRefConfig> auto_ref_configs_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_engine_2fssl_5fgc_5fengine_5fconfig_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Config_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Config

// map<string, .Config.Behavior> game_event_behavior = 1 [json_name = "gameEventBehavior"];
inline int Config::_internal_game_event_behavior_size() const {
  return _internal_game_event_behavior().size();
}
inline int Config::game_event_behavior_size() const {
  return _internal_game_event_behavior_size();
}
inline void Config::clear_game_event_behavior() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_event_behavior_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::google::protobuf::Map<::std::string, ::Config_Behavior>& Config::_internal_game_event_behavior() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_event_behavior_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::Config_Behavior>& Config::game_event_behavior() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Config.game_event_behavior)
  return _internal_game_event_behavior();
}
inline ::google::protobuf::Map<::std::string, ::Config_Behavior>* PROTOBUF_NONNULL Config::_internal_mutable_game_event_behavior() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.game_event_behavior_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::Config_Behavior>* PROTOBUF_NONNULL Config::mutable_game_event_behavior()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_mutable_map:Config.game_event_behavior)
  return _internal_mutable_game_event_behavior();
}

// map<string, .AutoRefConfig> auto_ref_configs = 2 [json_name = "autoRefConfigs"];
inline int Config::_internal_auto_ref_configs_size() const {
  return _internal_auto_ref_configs().size();
}
inline int Config::auto_ref_configs_size() const {
  return _internal_auto_ref_configs_size();
}
inline void Config::clear_auto_ref_configs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auto_ref_configs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::google::protobuf::Map<::std::string, ::AutoRefConfig>& Config::_internal_auto_ref_configs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.auto_ref_configs_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::AutoRefConfig>& Config::auto_ref_configs() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Config.auto_ref_configs)
  return _internal_auto_ref_configs();
}
inline ::google::protobuf::Map<::std::string, ::AutoRefConfig>* PROTOBUF_NONNULL Config::_internal_mutable_auto_ref_configs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.auto_ref_configs_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::AutoRefConfig>* PROTOBUF_NONNULL Config::mutable_auto_ref_configs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_mutable_map:Config.auto_ref_configs)
  return _internal_mutable_auto_ref_configs();
}

// optional string active_tracker_source = 3 [json_name = "activeTrackerSource"];
inline bool Config::has_active_tracker_source() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Config::clear_active_tracker_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.active_tracker_source_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Config::active_tracker_source() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Config.active_tracker_source)
  return _internal_active_tracker_source();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Config::set_active_tracker_source(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.active_tracker_source_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Config.active_tracker_source)
}
inline ::std::string* PROTOBUF_NONNULL Config::mutable_active_tracker_source()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_active_tracker_source();
  // @@protoc_insertion_point(field_mutable:Config.active_tracker_source)
  return _s;
}
inline const ::std::string& Config::_internal_active_tracker_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.active_tracker_source_.Get();
}
inline void Config::_internal_set_active_tracker_source(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.active_tracker_source_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Config::_internal_mutable_active_tracker_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.active_tracker_source_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Config::release_active_tracker_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Config.active_tracker_source)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.active_tracker_source_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.active_tracker_source_.Set("", GetArena());
  }
  return released;
}
inline void Config::set_allocated_active_tracker_source(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.active_tracker_source_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.active_tracker_source_.IsDefault()) {
    _impl_.active_tracker_source_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Config.active_tracker_source)
}

// repeated string teams = 4 [json_name = "teams"];
inline int Config::_internal_teams_size() const {
  return _internal_teams().size();
}
inline int Config::teams_size() const {
  return _internal_teams_size();
}
inline void Config::clear_teams() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.teams_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL Config::add_teams()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_teams()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:Config.teams)
  return _s;
}
inline const ::std::string& Config::teams(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Config.teams)
  return _internal_teams().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Config::mutable_teams(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Config.teams)
  return _internal_mutable_teams()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Config::set_teams(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_teams()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:Config.teams)
}
template <typename Arg_, typename... Args_>
inline void Config::add_teams(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_teams(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:Config.teams)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Config::teams()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Config.teams)
  return _internal_teams();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Config::mutable_teams() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:Config.teams)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_teams();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Config::_internal_teams() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.teams_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Config::_internal_mutable_teams() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.teams_;
}

// optional bool auto_continue = 5 [json_name = "autoContinue"];
inline bool Config::has_auto_continue() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Config::clear_auto_continue() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auto_continue_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool Config::auto_continue() const {
  // @@protoc_insertion_point(field_get:Config.auto_continue)
  return _internal_auto_continue();
}
inline void Config::set_auto_continue(bool value) {
  _internal_set_auto_continue(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Config.auto_continue)
}
inline bool Config::_internal_auto_continue() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.auto_continue_;
}
inline void Config::_internal_set_auto_continue(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auto_continue_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// AutoRefConfig

// map<string, .AutoRefConfig.Behavior> game_event_behavior = 1 [json_name = "gameEventBehavior"];
inline int AutoRefConfig::_internal_game_event_behavior_size() const {
  return _internal_game_event_behavior().size();
}
inline int AutoRefConfig::game_event_behavior_size() const {
  return _internal_game_event_behavior_size();
}
inline void AutoRefConfig::clear_game_event_behavior() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_event_behavior_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>& AutoRefConfig::_internal_game_event_behavior() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_event_behavior_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>& AutoRefConfig::game_event_behavior() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:AutoRefConfig.game_event_behavior)
  return _internal_game_event_behavior();
}
inline ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>* PROTOBUF_NONNULL AutoRefConfig::_internal_mutable_game_event_behavior() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.game_event_behavior_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::AutoRefConfig_Behavior>* PROTOBUF_NONNULL AutoRefConfig::mutable_game_event_behavior()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_map:AutoRefConfig.game_event_behavior)
  return _internal_mutable_game_event_behavior();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Config_Behavior> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Config_Behavior>() {
  return ::Config_Behavior_descriptor();
}
template <>
struct is_proto_enum<::AutoRefConfig_Behavior> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::AutoRefConfig_Behavior>() {
  return ::AutoRefConfig_Behavior_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // engine_2fssl_5fgc_5fengine_5fconfig_2eproto_2epb_2eh
