[package]
name = "vision-filter-replay"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
core_dump = { git = "https://github.com/Technulgy-LGNU/core-dump" }
crossterm = "0.29"
futures-util = "0.3"
loguna = { git = "https://github.com/Technulgy-LGNU/loguna", rev = "35dbc333412512c053b2f3711d2cf5ab0d9580ef" }
prost = "0.14"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite = "0.29"
toml = "1"
webinterface-assets = { git = "https://github.com/Technulgy-LGNU/CrashPilot-Interface", rev = "e1df0dad5177b37451ad987914e740ad16c93661" }
webinterface-core = { git = "https://github.com/Technulgy-LGNU/CrashPilot-Interface", rev = "e1df0dad5177b37451ad987914e740ad16c93661" }
webinterface-crashpilot-bridge = { git = "https://github.com/Technulgy-LGNU/CrashPilot-Interface", rev = "e1df0dad5177b37451ad987914e740ad16c93661" }
webinterface-protocol = { git = "https://github.com/Technulgy-LGNU/CrashPilot-Interface", rev = "e1df0dad5177b37451ad987914e740ad16c93661" }

[features]
default = []
loki = []
prometheus = []
