// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rcon/ssl_gc_rcon_autoref.proto
// Protobuf C++ Version: 7.34.1

#ifndef rcon_2fssl_5fgc_5frcon_5fautoref_2eproto_2epb_2eh
#define rcon_2fssl_5fgc_5frcon_5fautoref_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "state/ssl_gc_game_event.pb.h"
#include "rcon/ssl_gc_rcon.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rcon_2fssl_5fgc_5frcon_5fautoref_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rcon_2fssl_5fgc_5frcon_5fautoref_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_rcon_2fssl_5fgc_5frcon_5fautoref_2eproto;
}  // extern "C"
class AutoRefRegistration;
struct AutoRefRegistrationDefaultTypeInternal;
extern AutoRefRegistrationDefaultTypeInternal _AutoRefRegistration_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AutoRefRegistration_class_data_;
class AutoRefToController;
struct AutoRefToControllerDefaultTypeInternal;
extern AutoRefToControllerDefaultTypeInternal _AutoRefToController_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AutoRefToController_class_data_;
class ControllerToAutoRef;
struct ControllerToAutoRefDefaultTypeInternal;
extern ControllerToAutoRefDefaultTypeInternal _ControllerToAutoRef_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ControllerToAutoRef_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ControllerToAutoRef final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ControllerToAutoRef) */ {
 public:
  inline ControllerToAutoRef() : ControllerToAutoRef(nullptr) {}
  ~ControllerToAutoRef() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ControllerToAutoRef* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ControllerToAutoRef));
  }
#endif

  template <typename = void>
  explicit constexpr ControllerToAutoRef(::google::protobuf::internal::ConstantInitialized);

  inline ControllerToAutoRef(const ControllerToAutoRef& from) : ControllerToAutoRef(nullptr, from) {}
  inline ControllerToAutoRef(ControllerToAutoRef&& from) noexcept
      : ControllerToAutoRef(nullptr, ::std::move(from)) {}
  inline ControllerToAutoRef& operator=(const ControllerToAutoRef& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControllerToAutoRef& operator=(ControllerToAutoRef&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ControllerToAutoRef& default_instance() {
    return *reinterpret_cast<const ControllerToAutoRef*>(
        &_ControllerToAutoRef_default_instance_);
  }
  enum MsgCase {
    kControllerReply = 1,
    MSG_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ControllerToAutoRef& a, ControllerToAutoRef& b) { a.Swap(&b); }
  inline void Swap(ControllerToAutoRef* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControllerToAutoRef* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ControllerToAutoRef* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ControllerToAutoRef>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControllerToAutoRef& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ControllerToAutoRef& from) { ControllerToAutoRef::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ControllerToAutoRef* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ControllerToAutoRef"; }

  explicit ControllerToAutoRef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ControllerToAutoRef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ControllerToAutoRef& from);
  ControllerToAutoRef(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ControllerToAutoRef&& from) noexcept
      : ControllerToAutoRef(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kControllerReplyFieldNumber = 1,
  };
  // .ControllerReply controller_reply = 1 [json_name = "controllerReply"];
  [[nodiscard]] bool has_controller_reply()
      const;
  private:
  bool _internal_has_controller_reply() const;

  public:
  void clear_controller_reply() ;
  [[nodiscard]] const ::ControllerReply& controller_reply() const;
  [[nodiscard]] ::ControllerReply* PROTOBUF_NULLABLE release_controller_reply();
  ::ControllerReply* PROTOBUF_NONNULL mutable_controller_reply();
  void set_allocated_controller_reply(::ControllerReply* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_controller_reply(::ControllerReply* PROTOBUF_NULLABLE value);
  ::ControllerReply* PROTOBUF_NULLABLE unsafe_arena_release_controller_reply();

  private:
  const ::ControllerReply& _internal_controller_reply() const;
  ::ControllerReply* PROTOBUF_NONNULL _internal_mutable_controller_reply();

  public:
  void clear_msg();
  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:ControllerToAutoRef)
 private:
  class _Internal;
  void set_has_controller_reply();
  [[nodiscard]] inline bool has_msg() const;
  inline void clear_has_msg();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ControllerToAutoRef& from_msg);
    union MsgUnion {
      constexpr MsgUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::ControllerReply* PROTOBUF_NULLABLE controller_reply_;
    } msg_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rcon_2fssl_5fgc_5frcon_5fautoref_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ControllerToAutoRef_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AutoRefRegistration final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AutoRefRegistration) */ {
 public:
  inline AutoRefRegistration() : AutoRefRegistration(nullptr) {}
  ~AutoRefRegistration() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AutoRefRegistration* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AutoRefRegistration));
  }
#endif

  template <typename = void>
  explicit constexpr AutoRefRegistration(::google::protobuf::internal::ConstantInitialized);

  inline AutoRefRegistration(const AutoRefRegistration& from) : AutoRefRegistration(nullptr, from) {}
  inline AutoRefRegistration(AutoRefRegistration&& from) noexcept
      : AutoRefRegistration(nullptr, ::std::move(from)) {}
  inline AutoRefRegistration& operator=(const AutoRefRegistration& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutoRefRegistration& operator=(AutoRefRegistration&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AutoRefRegistration& default_instance() {
    return *reinterpret_cast<const AutoRefRegistration*>(
        &_AutoRefRegistration_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AutoRefRegistration& a, AutoRefRegistration& b) { a.Swap(&b); }
  inline void Swap(AutoRefRegistration* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutoRefRegistration* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AutoRefRegistration* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AutoRefRegistration>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutoRefRegistration& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutoRefRegistration& from) { AutoRefRegistration::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AutoRefRegistration* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AutoRefRegistration"; }

  explicit AutoRefRegistration(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AutoRefRegistration(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AutoRefRegistration& from);
  AutoRefRegistration(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AutoRefRegistration&& from) noexcept
      : AutoRefRegistration(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdentifierFieldNumber = 1,
    kSignatureFieldNumber = 2,
  };
  // required string identifier = 1 [json_name = "identifier"];
  [[nodiscard]] bool has_identifier()
      const;
  void clear_identifier() ;
  [[nodiscard]] const ::std::string& identifier() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_identifier(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_identifier();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_identifier();
  void set_allocated_identifier(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_identifier() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_identifier(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_identifier();

  public:
  // optional .Signature signature = 2 [json_name = "signature"];
  [[nodiscard]] bool has_signature()
      const;
  void clear_signature() ;
  [[nodiscard]] const ::Signature& signature() const;
  [[nodiscard]] ::Signature* PROTOBUF_NULLABLE release_signature();
  ::Signature* PROTOBUF_NONNULL mutable_signature();
  void set_allocated_signature(::Signature* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_signature(::Signature* PROTOBUF_NULLABLE value);
  ::Signature* PROTOBUF_NULLABLE unsafe_arena_release_signature();

  private:
  const ::Signature& _internal_signature() const;
  ::Signature* PROTOBUF_NONNULL _internal_mutable_signature();

  public:
  // @@protoc_insertion_point(class_scope:AutoRefRegistration)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AutoRefRegistration& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr identifier_;
    ::Signature* PROTOBUF_NULLABLE signature_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rcon_2fssl_5fgc_5frcon_5fautoref_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AutoRefRegistration_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AutoRefToController final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AutoRefToController) */ {
 public:
  inline AutoRefToController() : AutoRefToController(nullptr) {}
  ~AutoRefToController() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AutoRefToController* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AutoRefToController));
  }
#endif

  template <typename = void>
  explicit constexpr AutoRefToController(::google::protobuf::internal::ConstantInitialized);

  inline AutoRefToController(const AutoRefToController& from) : AutoRefToController(nullptr, from) {}
  inline AutoRefToController(AutoRefToController&& from) noexcept
      : AutoRefToController(nullptr, ::std::move(from)) {}
  inline AutoRefToController& operator=(const AutoRefToController& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutoRefToController& operator=(AutoRefToController&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AutoRefToController& default_instance() {
    return *reinterpret_cast<const AutoRefToController*>(
        &_AutoRefToController_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AutoRefToController& a, AutoRefToController& b) { a.Swap(&b); }
  inline void Swap(AutoRefToController* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutoRefToController* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AutoRefToController* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AutoRefToController>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutoRefToController& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutoRefToController& from) { AutoRefToController::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AutoRefToController* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AutoRefToController"; }

  explicit AutoRefToController(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AutoRefToController(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AutoRefToController& from);
  AutoRefToController(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AutoRefToController&& from) noexcept
      : AutoRefToController(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSignatureFieldNumber = 1,
    kGameEventFieldNumber = 2,
  };
  // optional .Signature signature = 1 [json_name = "signature"];
  [[nodiscard]] bool has_signature()
      const;
  void clear_signature() ;
  [[nodiscard]] const ::Signature& signature() const;
  [[nodiscard]] ::Signature* PROTOBUF_NULLABLE release_signature();
  ::Signature* PROTOBUF_NONNULL mutable_signature();
  void set_allocated_signature(::Signature* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_signature(::Signature* PROTOBUF_NULLABLE value);
  ::Signature* PROTOBUF_NULLABLE unsafe_arena_release_signature();

  private:
  const ::Signature& _internal_signature() const;
  ::Signature* PROTOBUF_NONNULL _internal_mutable_signature();

  public:
  // optional .GameEvent game_event = 2 [json_name = "gameEvent"];
  [[nodiscard]] bool has_game_event()
      const;
  void clear_game_event() ;
  [[nodiscard]] const ::GameEvent& game_event() const;
  [[nodiscard]] ::GameEvent* PROTOBUF_NULLABLE release_game_event();
  ::GameEvent* PROTOBUF_NONNULL mutable_game_event();
  void set_allocated_game_event(::GameEvent* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_game_event(::GameEvent* PROTOBUF_NULLABLE value);
  ::GameEvent* PROTOBUF_NULLABLE unsafe_arena_release_game_event();

  private:
  const ::GameEvent& _internal_game_event() const;
  ::GameEvent* PROTOBUF_NONNULL _internal_mutable_game_event();

  public:
  // @@protoc_insertion_point(class_scope:AutoRefToController)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AutoRefToController& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Signature* PROTOBUF_NULLABLE signature_;
    ::GameEvent* PROTOBUF_NULLABLE game_event_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rcon_2fssl_5fgc_5frcon_5fautoref_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AutoRefToController_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AutoRefRegistration

// required string identifier = 1 [json_name = "identifier"];
inline bool AutoRefRegistration::has_identifier() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void AutoRefRegistration::clear_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identifier_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& AutoRefRegistration::identifier() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefRegistration.identifier)
  return _internal_identifier();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AutoRefRegistration::set_identifier(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.identifier_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:AutoRefRegistration.identifier)
}
inline ::std::string* PROTOBUF_NONNULL AutoRefRegistration::mutable_identifier()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_identifier();
  // @@protoc_insertion_point(field_mutable:AutoRefRegistration.identifier)
  return _s;
}
inline const ::std::string& AutoRefRegistration::_internal_identifier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identifier_.Get();
}
inline void AutoRefRegistration::_internal_set_identifier(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identifier_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AutoRefRegistration::_internal_mutable_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.identifier_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AutoRefRegistration::release_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefRegistration.identifier)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.identifier_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.identifier_.Set("", GetArena());
  }
  return released;
}
inline void AutoRefRegistration::set_allocated_identifier(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.identifier_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identifier_.IsDefault()) {
    _impl_.identifier_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:AutoRefRegistration.identifier)
}

// optional .Signature signature = 2 [json_name = "signature"];
inline bool AutoRefRegistration::has_signature() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.signature_ != nullptr);
  return value;
}
inline const ::Signature& AutoRefRegistration::_internal_signature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Signature* p = _impl_.signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::Signature&>(::_Signature_default_instance_);
}
inline const ::Signature& AutoRefRegistration::signature() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefRegistration.signature)
  return _internal_signature();
}
inline void AutoRefRegistration::unsafe_arena_set_allocated_signature(
    ::Signature* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signature_);
  }
  _impl_.signature_ = reinterpret_cast<::Signature*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AutoRefRegistration.signature)
}
inline ::Signature* PROTOBUF_NULLABLE AutoRefRegistration::release_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Signature* released = _impl_.signature_;
  _impl_.signature_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Signature* PROTOBUF_NULLABLE AutoRefRegistration::unsafe_arena_release_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefRegistration.signature)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Signature* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
  return temp;
}
inline ::Signature* PROTOBUF_NONNULL AutoRefRegistration::_internal_mutable_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.signature_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Signature>(GetArena());
    _impl_.signature_ = reinterpret_cast<::Signature*>(p);
  }
  return _impl_.signature_;
}
inline ::Signature* PROTOBUF_NONNULL AutoRefRegistration::mutable_signature()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Signature* _msg = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:AutoRefRegistration.signature)
  return _msg;
}
inline void AutoRefRegistration::set_allocated_signature(::Signature* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signature_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.signature_ = reinterpret_cast<::Signature*>(value);
  // @@protoc_insertion_point(field_set_allocated:AutoRefRegistration.signature)
}

// -------------------------------------------------------------------

// AutoRefToController

// optional .Signature signature = 1 [json_name = "signature"];
inline bool AutoRefToController::has_signature() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.signature_ != nullptr);
  return value;
}
inline const ::Signature& AutoRefToController::_internal_signature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Signature* p = _impl_.signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::Signature&>(::_Signature_default_instance_);
}
inline const ::Signature& AutoRefToController::signature() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefToController.signature)
  return _internal_signature();
}
inline void AutoRefToController::unsafe_arena_set_allocated_signature(
    ::Signature* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signature_);
  }
  _impl_.signature_ = reinterpret_cast<::Signature*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AutoRefToController.signature)
}
inline ::Signature* PROTOBUF_NULLABLE AutoRefToController::release_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::Signature* released = _impl_.signature_;
  _impl_.signature_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Signature* PROTOBUF_NULLABLE AutoRefToController::unsafe_arena_release_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefToController.signature)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::Signature* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
  return temp;
}
inline ::Signature* PROTOBUF_NONNULL AutoRefToController::_internal_mutable_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.signature_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Signature>(GetArena());
    _impl_.signature_ = reinterpret_cast<::Signature*>(p);
  }
  return _impl_.signature_;
}
inline ::Signature* PROTOBUF_NONNULL AutoRefToController::mutable_signature()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::Signature* _msg = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:AutoRefToController.signature)
  return _msg;
}
inline void AutoRefToController::set_allocated_signature(::Signature* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signature_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.signature_ = reinterpret_cast<::Signature*>(value);
  // @@protoc_insertion_point(field_set_allocated:AutoRefToController.signature)
}

// optional .GameEvent game_event = 2 [json_name = "gameEvent"];
inline bool AutoRefToController::has_game_event() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.game_event_ != nullptr);
  return value;
}
inline const ::GameEvent& AutoRefToController::_internal_game_event() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameEvent* p = _impl_.game_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameEvent&>(::_GameEvent_default_instance_);
}
inline const ::GameEvent& AutoRefToController::game_event() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefToController.game_event)
  return _internal_game_event();
}
inline void AutoRefToController::unsafe_arena_set_allocated_game_event(
    ::GameEvent* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.game_event_);
  }
  _impl_.game_event_ = reinterpret_cast<::GameEvent*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AutoRefToController.game_event)
}
inline ::GameEvent* PROTOBUF_NULLABLE AutoRefToController::release_game_event() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::GameEvent* released = _impl_.game_event_;
  _impl_.game_event_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameEvent* PROTOBUF_NULLABLE AutoRefToController::unsafe_arena_release_game_event() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefToController.game_event)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::GameEvent* temp = _impl_.game_event_;
  _impl_.game_event_ = nullptr;
  return temp;
}
inline ::GameEvent* PROTOBUF_NONNULL AutoRefToController::_internal_mutable_game_event() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.game_event_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameEvent>(GetArena());
    _impl_.game_event_ = reinterpret_cast<::GameEvent*>(p);
  }
  return _impl_.game_event_;
}
inline ::GameEvent* PROTOBUF_NONNULL AutoRefToController::mutable_game_event()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::GameEvent* _msg = _internal_mutable_game_event();
  // @@protoc_insertion_point(field_mutable:AutoRefToController.game_event)
  return _msg;
}
inline void AutoRefToController::set_allocated_game_event(::GameEvent* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.game_event_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.game_event_ = reinterpret_cast<::GameEvent*>(value);
  // @@protoc_insertion_point(field_set_allocated:AutoRefToController.game_event)
}

// -------------------------------------------------------------------

// ControllerToAutoRef

// .ControllerReply controller_reply = 1 [json_name = "controllerReply"];
inline bool ControllerToAutoRef::has_controller_reply() const {
  return msg_case() == kControllerReply;
}
inline bool ControllerToAutoRef::_internal_has_controller_reply() const {
  return msg_case() == kControllerReply;
}
inline void ControllerToAutoRef::set_has_controller_reply() {
  _impl_._oneof_case_[0] = kControllerReply;
}
inline ::ControllerReply* PROTOBUF_NULLABLE ControllerToAutoRef::release_controller_reply() {
  // @@protoc_insertion_point(field_release:ControllerToAutoRef.controller_reply)
  if (msg_case() == kControllerReply) {
    clear_has_msg();
    auto* temp = _impl_.msg_.controller_reply_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.msg_.controller_reply_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ControllerReply& ControllerToAutoRef::_internal_controller_reply() const {
  return msg_case() == kControllerReply ? static_cast<const ::ControllerReply&>(*_impl_.msg_.controller_reply_)
                     : reinterpret_cast<const ::ControllerReply&>(::_ControllerReply_default_instance_);
}
inline const ::ControllerReply& ControllerToAutoRef::controller_reply() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ControllerToAutoRef.controller_reply)
  return _internal_controller_reply();
}
inline ::ControllerReply* PROTOBUF_NULLABLE ControllerToAutoRef::unsafe_arena_release_controller_reply() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ControllerToAutoRef.controller_reply)
  if (msg_case() == kControllerReply) {
    clear_has_msg();
    auto* temp = _impl_.msg_.controller_reply_;
    _impl_.msg_.controller_reply_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ControllerToAutoRef::unsafe_arena_set_allocated_controller_reply(
    ::ControllerReply* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_msg();
  if (value) {
    set_has_controller_reply();
    _impl_.msg_.controller_reply_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ControllerToAutoRef.controller_reply)
}
inline ::ControllerReply* PROTOBUF_NONNULL ControllerToAutoRef::_internal_mutable_controller_reply() {
  if (msg_case() != kControllerReply) {
    clear_msg();
    set_has_controller_reply();
    _impl_.msg_.controller_reply_ = 
        ::google::protobuf::Message::DefaultConstruct<::ControllerReply>(GetArena());
  }
  return _impl_.msg_.controller_reply_;
}
inline ::ControllerReply* PROTOBUF_NONNULL ControllerToAutoRef::mutable_controller_reply()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::ControllerReply* _msg = _internal_mutable_controller_reply();
  // @@protoc_insertion_point(field_mutable:ControllerToAutoRef.controller_reply)
  return _msg;
}

inline bool ControllerToAutoRef::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void ControllerToAutoRef::clear_has_msg() {
  _impl_._oneof_case_[0] = MSG_NOT_SET;
}
inline ControllerToAutoRef::MsgCase ControllerToAutoRef::msg_case() const {
  return ControllerToAutoRef::MsgCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // rcon_2fssl_5fgc_5frcon_5fautoref_2eproto_2epb_2eh
