// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ci/autoref/ssl_autoref_ci.proto
// Protobuf C++ Version: 7.34.1

#ifndef ci_2fautoref_2fssl_5fautoref_5fci_2eproto_2epb_2eh
#define ci_2fautoref_2fssl_5fautoref_5fci_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "vision_tracked/messages_robocup_ssl_detection.pb.h"
#include "vision_tracked/messages_robocup_ssl_geometry.pb.h"
#include "state/ssl_gc_referee_message.pb.h"
#include "vision_tracked/messages_robocup_ssl_wrapper_tracked.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ci_2fautoref_2fssl_5fautoref_5fci_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ci_2fautoref_2fssl_5fautoref_5fci_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ci_2fautoref_2fssl_5fautoref_5fci_2eproto;
}  // extern "C"
class AutoRefCiInput;
struct AutoRefCiInputDefaultTypeInternal;
extern AutoRefCiInputDefaultTypeInternal _AutoRefCiInput_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AutoRefCiInput_class_data_;
class AutoRefCiOutput;
struct AutoRefCiOutputDefaultTypeInternal;
extern AutoRefCiOutputDefaultTypeInternal _AutoRefCiOutput_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AutoRefCiOutput_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AutoRefCiOutput final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AutoRefCiOutput) */ {
 public:
  inline AutoRefCiOutput() : AutoRefCiOutput(nullptr) {}
  ~AutoRefCiOutput() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AutoRefCiOutput* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AutoRefCiOutput));
  }
#endif

  template <typename = void>
  explicit constexpr AutoRefCiOutput(::google::protobuf::internal::ConstantInitialized);

  inline AutoRefCiOutput(const AutoRefCiOutput& from) : AutoRefCiOutput(nullptr, from) {}
  inline AutoRefCiOutput(AutoRefCiOutput&& from) noexcept
      : AutoRefCiOutput(nullptr, ::std::move(from)) {}
  inline AutoRefCiOutput& operator=(const AutoRefCiOutput& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutoRefCiOutput& operator=(AutoRefCiOutput&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AutoRefCiOutput& default_instance() {
    return *reinterpret_cast<const AutoRefCiOutput*>(
        &_AutoRefCiOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AutoRefCiOutput& a, AutoRefCiOutput& b) { a.Swap(&b); }
  inline void Swap(AutoRefCiOutput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutoRefCiOutput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AutoRefCiOutput* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AutoRefCiOutput>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutoRefCiOutput& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutoRefCiOutput& from) { AutoRefCiOutput::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AutoRefCiOutput* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AutoRefCiOutput"; }

  explicit AutoRefCiOutput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AutoRefCiOutput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AutoRefCiOutput& from);
  AutoRefCiOutput(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AutoRefCiOutput&& from) noexcept
      : AutoRefCiOutput(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTrackerWrapperPacketFieldNumber = 1,
  };
  // optional .TrackerWrapperPacket tracker_wrapper_packet = 1 [json_name = "trackerWrapperPacket"];
  [[nodiscard]] bool has_tracker_wrapper_packet()
      const;
  void clear_tracker_wrapper_packet() ;
  [[nodiscard]] const ::TrackerWrapperPacket& tracker_wrapper_packet() const;
  [[nodiscard]] ::TrackerWrapperPacket* PROTOBUF_NULLABLE release_tracker_wrapper_packet();
  ::TrackerWrapperPacket* PROTOBUF_NONNULL mutable_tracker_wrapper_packet();
  void set_allocated_tracker_wrapper_packet(::TrackerWrapperPacket* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_tracker_wrapper_packet(::TrackerWrapperPacket* PROTOBUF_NULLABLE value);
  ::TrackerWrapperPacket* PROTOBUF_NULLABLE unsafe_arena_release_tracker_wrapper_packet();

  private:
  const ::TrackerWrapperPacket& _internal_tracker_wrapper_packet() const;
  ::TrackerWrapperPacket* PROTOBUF_NONNULL _internal_mutable_tracker_wrapper_packet();

  public:
  // @@protoc_insertion_point(class_scope:AutoRefCiOutput)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AutoRefCiOutput& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::TrackerWrapperPacket* PROTOBUF_NULLABLE tracker_wrapper_packet_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ci_2fautoref_2fssl_5fautoref_5fci_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AutoRefCiOutput_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AutoRefCiInput final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AutoRefCiInput) */ {
 public:
  inline AutoRefCiInput() : AutoRefCiInput(nullptr) {}
  ~AutoRefCiInput() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AutoRefCiInput* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AutoRefCiInput));
  }
#endif

  template <typename = void>
  explicit constexpr AutoRefCiInput(::google::protobuf::internal::ConstantInitialized);

  inline AutoRefCiInput(const AutoRefCiInput& from) : AutoRefCiInput(nullptr, from) {}
  inline AutoRefCiInput(AutoRefCiInput&& from) noexcept
      : AutoRefCiInput(nullptr, ::std::move(from)) {}
  inline AutoRefCiInput& operator=(const AutoRefCiInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutoRefCiInput& operator=(AutoRefCiInput&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AutoRefCiInput& default_instance() {
    return *reinterpret_cast<const AutoRefCiInput*>(
        &_AutoRefCiInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AutoRefCiInput& a, AutoRefCiInput& b) { a.Swap(&b); }
  inline void Swap(AutoRefCiInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutoRefCiInput* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AutoRefCiInput* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AutoRefCiInput>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutoRefCiInput& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutoRefCiInput& from) { AutoRefCiInput::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AutoRefCiInput* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AutoRefCiInput"; }

  explicit AutoRefCiInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AutoRefCiInput(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AutoRefCiInput& from);
  AutoRefCiInput(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AutoRefCiInput&& from) noexcept
      : AutoRefCiInput(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDetectionFieldNumber = 3,
    kRefereeMessageFieldNumber = 1,
    kTrackerWrapperPacketFieldNumber = 2,
    kGeometryFieldNumber = 4,
  };
  // repeated .SSL_DetectionFrame detection = 3 [json_name = "detection"];
  [[nodiscard]] int detection_size()
      const;
  private:
  int _internal_detection_size() const;

  public:
  void clear_detection() ;
  [[nodiscard]] ::SSL_DetectionFrame* PROTOBUF_NONNULL mutable_detection(int index);
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>* PROTOBUF_NONNULL
  mutable_detection();

  private:
  const ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>& _internal_detection() const;
  ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>* PROTOBUF_NONNULL _internal_mutable_detection();
  public:
  [[nodiscard]] const ::SSL_DetectionFrame& detection(int index) const;
  ::SSL_DetectionFrame* PROTOBUF_NONNULL add_detection();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>& detection()
      const;
  // optional .Referee referee_message = 1 [json_name = "refereeMessage"];
  [[nodiscard]] bool has_referee_message()
      const;
  void clear_referee_message() ;
  [[nodiscard]] const ::Referee& referee_message() const;
  [[nodiscard]] ::Referee* PROTOBUF_NULLABLE release_referee_message();
  ::Referee* PROTOBUF_NONNULL mutable_referee_message();
  void set_allocated_referee_message(::Referee* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_referee_message(::Referee* PROTOBUF_NULLABLE value);
  ::Referee* PROTOBUF_NULLABLE unsafe_arena_release_referee_message();

  private:
  const ::Referee& _internal_referee_message() const;
  ::Referee* PROTOBUF_NONNULL _internal_mutable_referee_message();

  public:
  // optional .TrackerWrapperPacket tracker_wrapper_packet = 2 [json_name = "trackerWrapperPacket"];
  [[nodiscard]] bool has_tracker_wrapper_packet()
      const;
  void clear_tracker_wrapper_packet() ;
  [[nodiscard]] const ::TrackerWrapperPacket& tracker_wrapper_packet() const;
  [[nodiscard]] ::TrackerWrapperPacket* PROTOBUF_NULLABLE release_tracker_wrapper_packet();
  ::TrackerWrapperPacket* PROTOBUF_NONNULL mutable_tracker_wrapper_packet();
  void set_allocated_tracker_wrapper_packet(::TrackerWrapperPacket* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_tracker_wrapper_packet(::TrackerWrapperPacket* PROTOBUF_NULLABLE value);
  ::TrackerWrapperPacket* PROTOBUF_NULLABLE unsafe_arena_release_tracker_wrapper_packet();

  private:
  const ::TrackerWrapperPacket& _internal_tracker_wrapper_packet() const;
  ::TrackerWrapperPacket* PROTOBUF_NONNULL _internal_mutable_tracker_wrapper_packet();

  public:
  // optional .SSL_GeometryData geometry = 4 [json_name = "geometry"];
  [[nodiscard]] bool has_geometry()
      const;
  void clear_geometry() ;
  [[nodiscard]] const ::SSL_GeometryData& geometry() const;
  [[nodiscard]] ::SSL_GeometryData* PROTOBUF_NULLABLE release_geometry();
  ::SSL_GeometryData* PROTOBUF_NONNULL mutable_geometry();
  void set_allocated_geometry(::SSL_GeometryData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_geometry(::SSL_GeometryData* PROTOBUF_NULLABLE value);
  ::SSL_GeometryData* PROTOBUF_NULLABLE unsafe_arena_release_geometry();

  private:
  const ::SSL_GeometryData& _internal_geometry() const;
  ::SSL_GeometryData* PROTOBUF_NONNULL _internal_mutable_geometry();

  public:
  // @@protoc_insertion_point(class_scope:AutoRefCiInput)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AutoRefCiInput& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::SSL_DetectionFrame > detection_;
    ::Referee* PROTOBUF_NULLABLE referee_message_;
    ::TrackerWrapperPacket* PROTOBUF_NULLABLE tracker_wrapper_packet_;
    ::SSL_GeometryData* PROTOBUF_NULLABLE geometry_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ci_2fautoref_2fssl_5fautoref_5fci_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AutoRefCiInput_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AutoRefCiInput

// optional .Referee referee_message = 1 [json_name = "refereeMessage"];
inline bool AutoRefCiInput::has_referee_message() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.referee_message_ != nullptr);
  return value;
}
inline const ::Referee& AutoRefCiInput::_internal_referee_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Referee* p = _impl_.referee_message_;
  return p != nullptr ? *p : reinterpret_cast<const ::Referee&>(::_Referee_default_instance_);
}
inline const ::Referee& AutoRefCiInput::referee_message() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefCiInput.referee_message)
  return _internal_referee_message();
}
inline void AutoRefCiInput::unsafe_arena_set_allocated_referee_message(
    ::Referee* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.referee_message_);
  }
  _impl_.referee_message_ = reinterpret_cast<::Referee*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AutoRefCiInput.referee_message)
}
inline ::Referee* PROTOBUF_NULLABLE AutoRefCiInput::release_referee_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Referee* released = _impl_.referee_message_;
  _impl_.referee_message_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Referee* PROTOBUF_NULLABLE AutoRefCiInput::unsafe_arena_release_referee_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefCiInput.referee_message)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Referee* temp = _impl_.referee_message_;
  _impl_.referee_message_ = nullptr;
  return temp;
}
inline ::Referee* PROTOBUF_NONNULL AutoRefCiInput::_internal_mutable_referee_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.referee_message_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Referee>(GetArena());
    _impl_.referee_message_ = reinterpret_cast<::Referee*>(p);
  }
  return _impl_.referee_message_;
}
inline ::Referee* PROTOBUF_NONNULL AutoRefCiInput::mutable_referee_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::Referee* _msg = _internal_mutable_referee_message();
  // @@protoc_insertion_point(field_mutable:AutoRefCiInput.referee_message)
  return _msg;
}
inline void AutoRefCiInput::set_allocated_referee_message(::Referee* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.referee_message_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.referee_message_ = reinterpret_cast<::Referee*>(value);
  // @@protoc_insertion_point(field_set_allocated:AutoRefCiInput.referee_message)
}

// optional .TrackerWrapperPacket tracker_wrapper_packet = 2 [json_name = "trackerWrapperPacket"];
inline bool AutoRefCiInput::has_tracker_wrapper_packet() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.tracker_wrapper_packet_ != nullptr);
  return value;
}
inline const ::TrackerWrapperPacket& AutoRefCiInput::_internal_tracker_wrapper_packet() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::TrackerWrapperPacket* p = _impl_.tracker_wrapper_packet_;
  return p != nullptr ? *p : reinterpret_cast<const ::TrackerWrapperPacket&>(::_TrackerWrapperPacket_default_instance_);
}
inline const ::TrackerWrapperPacket& AutoRefCiInput::tracker_wrapper_packet() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefCiInput.tracker_wrapper_packet)
  return _internal_tracker_wrapper_packet();
}
inline void AutoRefCiInput::unsafe_arena_set_allocated_tracker_wrapper_packet(
    ::TrackerWrapperPacket* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tracker_wrapper_packet_);
  }
  _impl_.tracker_wrapper_packet_ = reinterpret_cast<::TrackerWrapperPacket*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AutoRefCiInput.tracker_wrapper_packet)
}
inline ::TrackerWrapperPacket* PROTOBUF_NULLABLE AutoRefCiInput::release_tracker_wrapper_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::TrackerWrapperPacket* released = _impl_.tracker_wrapper_packet_;
  _impl_.tracker_wrapper_packet_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::TrackerWrapperPacket* PROTOBUF_NULLABLE AutoRefCiInput::unsafe_arena_release_tracker_wrapper_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefCiInput.tracker_wrapper_packet)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::TrackerWrapperPacket* temp = _impl_.tracker_wrapper_packet_;
  _impl_.tracker_wrapper_packet_ = nullptr;
  return temp;
}
inline ::TrackerWrapperPacket* PROTOBUF_NONNULL AutoRefCiInput::_internal_mutable_tracker_wrapper_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.tracker_wrapper_packet_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::TrackerWrapperPacket>(GetArena());
    _impl_.tracker_wrapper_packet_ = reinterpret_cast<::TrackerWrapperPacket*>(p);
  }
  return _impl_.tracker_wrapper_packet_;
}
inline ::TrackerWrapperPacket* PROTOBUF_NONNULL AutoRefCiInput::mutable_tracker_wrapper_packet()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::TrackerWrapperPacket* _msg = _internal_mutable_tracker_wrapper_packet();
  // @@protoc_insertion_point(field_mutable:AutoRefCiInput.tracker_wrapper_packet)
  return _msg;
}
inline void AutoRefCiInput::set_allocated_tracker_wrapper_packet(::TrackerWrapperPacket* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tracker_wrapper_packet_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.tracker_wrapper_packet_ = reinterpret_cast<::TrackerWrapperPacket*>(value);
  // @@protoc_insertion_point(field_set_allocated:AutoRefCiInput.tracker_wrapper_packet)
}

// repeated .SSL_DetectionFrame detection = 3 [json_name = "detection"];
inline int AutoRefCiInput::_internal_detection_size() const {
  return _internal_detection().size();
}
inline int AutoRefCiInput::detection_size() const {
  return _internal_detection_size();
}
inline ::SSL_DetectionFrame* PROTOBUF_NONNULL AutoRefCiInput::mutable_detection(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:AutoRefCiInput.detection)
  return _internal_mutable_detection()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>* PROTOBUF_NONNULL AutoRefCiInput::mutable_detection()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:AutoRefCiInput.detection)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_detection();
}
inline const ::SSL_DetectionFrame& AutoRefCiInput::detection(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefCiInput.detection)
  return _internal_detection().Get(index);
}
inline ::SSL_DetectionFrame* PROTOBUF_NONNULL AutoRefCiInput::add_detection()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::SSL_DetectionFrame* _add =
      _internal_mutable_detection()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:AutoRefCiInput.detection)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>& AutoRefCiInput::detection() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:AutoRefCiInput.detection)
  return _internal_detection();
}
inline const ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>&
AutoRefCiInput::_internal_detection() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.detection_;
}
inline ::google::protobuf::RepeatedPtrField<::SSL_DetectionFrame>* PROTOBUF_NONNULL
AutoRefCiInput::_internal_mutable_detection() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.detection_;
}

// optional .SSL_GeometryData geometry = 4 [json_name = "geometry"];
inline bool AutoRefCiInput::has_geometry() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.geometry_ != nullptr);
  return value;
}
inline const ::SSL_GeometryData& AutoRefCiInput::_internal_geometry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::SSL_GeometryData* p = _impl_.geometry_;
  return p != nullptr ? *p : reinterpret_cast<const ::SSL_GeometryData&>(::_SSL_GeometryData_default_instance_);
}
inline const ::SSL_GeometryData& AutoRefCiInput::geometry() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefCiInput.geometry)
  return _internal_geometry();
}
inline void AutoRefCiInput::unsafe_arena_set_allocated_geometry(
    ::SSL_GeometryData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.geometry_);
  }
  _impl_.geometry_ = reinterpret_cast<::SSL_GeometryData*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AutoRefCiInput.geometry)
}
inline ::SSL_GeometryData* PROTOBUF_NULLABLE AutoRefCiInput::release_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::SSL_GeometryData* released = _impl_.geometry_;
  _impl_.geometry_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::SSL_GeometryData* PROTOBUF_NULLABLE AutoRefCiInput::unsafe_arena_release_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefCiInput.geometry)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::SSL_GeometryData* temp = _impl_.geometry_;
  _impl_.geometry_ = nullptr;
  return temp;
}
inline ::SSL_GeometryData* PROTOBUF_NONNULL AutoRefCiInput::_internal_mutable_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.geometry_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::SSL_GeometryData>(GetArena());
    _impl_.geometry_ = reinterpret_cast<::SSL_GeometryData*>(p);
  }
  return _impl_.geometry_;
}
inline ::SSL_GeometryData* PROTOBUF_NONNULL AutoRefCiInput::mutable_geometry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::SSL_GeometryData* _msg = _internal_mutable_geometry();
  // @@protoc_insertion_point(field_mutable:AutoRefCiInput.geometry)
  return _msg;
}
inline void AutoRefCiInput::set_allocated_geometry(::SSL_GeometryData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.geometry_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.geometry_ = reinterpret_cast<::SSL_GeometryData*>(value);
  // @@protoc_insertion_point(field_set_allocated:AutoRefCiInput.geometry)
}

// -------------------------------------------------------------------

// AutoRefCiOutput

// optional .TrackerWrapperPacket tracker_wrapper_packet = 1 [json_name = "trackerWrapperPacket"];
inline bool AutoRefCiOutput::has_tracker_wrapper_packet() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.tracker_wrapper_packet_ != nullptr);
  return value;
}
inline const ::TrackerWrapperPacket& AutoRefCiOutput::_internal_tracker_wrapper_packet() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::TrackerWrapperPacket* p = _impl_.tracker_wrapper_packet_;
  return p != nullptr ? *p : reinterpret_cast<const ::TrackerWrapperPacket&>(::_TrackerWrapperPacket_default_instance_);
}
inline const ::TrackerWrapperPacket& AutoRefCiOutput::tracker_wrapper_packet() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AutoRefCiOutput.tracker_wrapper_packet)
  return _internal_tracker_wrapper_packet();
}
inline void AutoRefCiOutput::unsafe_arena_set_allocated_tracker_wrapper_packet(
    ::TrackerWrapperPacket* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tracker_wrapper_packet_);
  }
  _impl_.tracker_wrapper_packet_ = reinterpret_cast<::TrackerWrapperPacket*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AutoRefCiOutput.tracker_wrapper_packet)
}
inline ::TrackerWrapperPacket* PROTOBUF_NULLABLE AutoRefCiOutput::release_tracker_wrapper_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::TrackerWrapperPacket* released = _impl_.tracker_wrapper_packet_;
  _impl_.tracker_wrapper_packet_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::TrackerWrapperPacket* PROTOBUF_NULLABLE AutoRefCiOutput::unsafe_arena_release_tracker_wrapper_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AutoRefCiOutput.tracker_wrapper_packet)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::TrackerWrapperPacket* temp = _impl_.tracker_wrapper_packet_;
  _impl_.tracker_wrapper_packet_ = nullptr;
  return temp;
}
inline ::TrackerWrapperPacket* PROTOBUF_NONNULL AutoRefCiOutput::_internal_mutable_tracker_wrapper_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.tracker_wrapper_packet_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::TrackerWrapperPacket>(GetArena());
    _impl_.tracker_wrapper_packet_ = reinterpret_cast<::TrackerWrapperPacket*>(p);
  }
  return _impl_.tracker_wrapper_packet_;
}
inline ::TrackerWrapperPacket* PROTOBUF_NONNULL AutoRefCiOutput::mutable_tracker_wrapper_packet()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::TrackerWrapperPacket* _msg = _internal_mutable_tracker_wrapper_packet();
  // @@protoc_insertion_point(field_mutable:AutoRefCiOutput.tracker_wrapper_packet)
  return _msg;
}
inline void AutoRefCiOutput::set_allocated_tracker_wrapper_packet(::TrackerWrapperPacket* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tracker_wrapper_packet_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.tracker_wrapper_packet_ = reinterpret_cast<::TrackerWrapperPacket*>(value);
  // @@protoc_insertion_point(field_set_allocated:AutoRefCiOutput.tracker_wrapper_packet)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // ci_2fautoref_2fssl_5fautoref_5fci_2eproto_2epb_2eh
