// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/ssl_gc_api.proto
// Protobuf C++ Version: 7.34.1

#include "api/ssl_gc_api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ProtocolEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        change_{nullptr},
        match_time_elapsed_{nullptr},
        stage_time_elapsed_{nullptr},
        id_{0} {}

template <typename>
constexpr ProtocolEntry::ProtocolEntry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ProtocolEntry_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ProtocolEntryDefaultTypeInternal {
  constexpr ProtocolEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtocolEntryDefaultTypeInternal() {}
  union {
    ProtocolEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtocolEntryDefaultTypeInternal _ProtocolEntry_default_instance_;

inline constexpr Input::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        change_{nullptr},
        config_delta_{nullptr},
        continue_action_{nullptr},
        reset_match_{false} {}

template <typename>
constexpr Input::Input(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Input_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct InputDefaultTypeInternal {
  constexpr InputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InputDefaultTypeInternal() {}
  union {
    Input _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InputDefaultTypeInternal _Input_default_instance_;

inline constexpr Protocol::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        entry_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::Protocol,
            PROTOBUF_FIELD_OFFSET(::Protocol, _impl_.entry_)>()
        }
        #else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        entry_ {}
        #endif
        ,
        delta_{false} {}

template <typename>
constexpr Protocol::Protocol(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Protocol_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ProtocolDefaultTypeInternal {
  constexpr ProtocolDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtocolDefaultTypeInternal() {}
  union {
    Protocol _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtocolDefaultTypeInternal _Protocol_default_instance_;

inline constexpr Output::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        match_state_{nullptr},
        gc_state_{nullptr},
        protocol_{nullptr},
        config_{nullptr} {}

template <typename>
constexpr Output::Output(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Output_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct OutputDefaultTypeInternal {
  constexpr OutputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OutputDefaultTypeInternal() {}
  union {
    Output _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OutputDefaultTypeInternal _Output_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_api_2fssl_5fgc_5fapi_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_api_2fssl_5fgc_5fapi_2eproto = nullptr;
const ::uint32_t
    TableStruct_api_2fssl_5fgc_5fapi_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Output, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Output, _impl_.match_state_),
        PROTOBUF_FIELD_OFFSET(::Output, _impl_.gc_state_),
        PROTOBUF_FIELD_OFFSET(::Output, _impl_.protocol_),
        PROTOBUF_FIELD_OFFSET(::Output, _impl_.config_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol, _impl_.delta_),
        PROTOBUF_FIELD_OFFSET(::Protocol, _impl_.entry_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ProtocolEntry, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ProtocolEntry, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::ProtocolEntry, _impl_.change_),
        PROTOBUF_FIELD_OFFSET(::ProtocolEntry, _impl_.match_time_elapsed_),
        PROTOBUF_FIELD_OFFSET(::ProtocolEntry, _impl_.stage_time_elapsed_),
        3,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Input, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Input, _impl_.change_),
        PROTOBUF_FIELD_OFFSET(::Input, _impl_.reset_match_),
        PROTOBUF_FIELD_OFFSET(::Input, _impl_.config_delta_),
        PROTOBUF_FIELD_OFFSET(::Input, _impl_.continue_action_),
        0,
        3,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Output)},
        {11, sizeof(::Protocol)},
        {18, sizeof(::ProtocolEntry)},
        {29, sizeof(::Input)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_Output_default_instance_._instance,
    &::_Protocol_default_instance_._instance,
    &::_ProtocolEntry_default_instance_._instance,
    &::_Input_default_instance_._instance,
};
const char descriptor_table_protodef_api_2fssl_5fgc_5fapi_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024api/ssl_gc_api.proto\032\030state/ssl_gc_sta"
    "te.proto\032 statemachine/ssl_gc_change.pro"
    "to\032\032engine/ssl_gc_engine.proto\032!engine/s"
    "sl_gc_engine_config.proto\032\036google/protob"
    "uf/duration.proto\"\236\001\n\006Output\022\'\n\013match_st"
    "ate\030\001 \001(\0132\006.StateR\nmatchState\022#\n\010gc_stat"
    "e\030\002 \001(\0132\010.GcStateR\007gcState\022%\n\010protocol\030\003"
    " \001(\0132\t.ProtocolR\010protocol\022\037\n\006config\030\004 \001("
    "\0132\007.ConfigR\006config\"F\n\010Protocol\022\024\n\005delta\030"
    "\001 \001(\010R\005delta\022$\n\005entry\030\002 \003(\0132\016.ProtocolEn"
    "tryR\005entry\"\322\001\n\rProtocolEntry\022\016\n\002id\030\001 \001(\005"
    "R\002id\022\037\n\006change\030\002 \001(\0132\007.ChangeR\006change\022G\n"
    "\022match_time_elapsed\030\003 \001(\0132\031.google.proto"
    "buf.DurationR\020matchTimeElapsed\022G\n\022stage_"
    "time_elapsed\030\004 \001(\0132\031.google.protobuf.Dur"
    "ationR\020stageTimeElapsed\"\257\001\n\005Input\022\037\n\006cha"
    "nge\030\001 \001(\0132\007.ChangeR\006change\022\037\n\013reset_matc"
    "h\030\002 \001(\010R\nresetMatch\022*\n\014config_delta\030\003 \001("
    "\0132\007.ConfigR\013configDelta\0228\n\017continue_acti"
    "on\030\004 \001(\0132\017.ContinueActionR\016continueActio"
    "nB\021B\rSslGcApiProtoP\001"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_api_2fssl_5fgc_5fapi_2eproto_deps[5] = {
        &::descriptor_table_engine_2fssl_5fgc_5fengine_2eproto,
        &::descriptor_table_engine_2fssl_5fgc_5fengine_5fconfig_2eproto,
        &::descriptor_table_google_2fprotobuf_2fduration_2eproto,
        &::descriptor_table_state_2fssl_5fgc_5fstate_2eproto,
        &::descriptor_table_statemachine_2fssl_5fgc_5fchange_2eproto,
};
static ::absl::once_flag descriptor_table_api_2fssl_5fgc_5fapi_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_2fssl_5fgc_5fapi_2eproto = {
    false,
    false,
    820,
    descriptor_table_protodef_api_2fssl_5fgc_5fapi_2eproto,
    "api/ssl_gc_api.proto",
    &descriptor_table_api_2fssl_5fgc_5fapi_2eproto_once,
    descriptor_table_api_2fssl_5fgc_5fapi_2eproto_deps,
    5,
    4,
    schemas,
    file_default_instances,
    TableStruct_api_2fssl_5fgc_5fapi_2eproto::offsets,
    file_level_enum_descriptors_api_2fssl_5fgc_5fapi_2eproto,
    file_level_service_descriptors_api_2fssl_5fgc_5fapi_2eproto,
};
// ===================================================================

class Output::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Output>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Output, _impl_._has_bits_);
};

void Output::clear_match_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.match_state_ != nullptr) _impl_.match_state_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
void Output::clear_gc_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.gc_state_ != nullptr) _impl_.gc_state_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void Output::clear_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.config_ != nullptr) _impl_.config_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
Output::Output(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Output_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Output)
}
PROTOBUF_NDEBUG_INLINE Output::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Output& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Output::Output(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Output& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Output_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Output* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.match_state_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.match_state_)
                : nullptr;
  _impl_.gc_state_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gc_state_)
                : nullptr;
  _impl_.protocol_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.protocol_)
                : nullptr;
  _impl_.config_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:Output)
}
PROTOBUF_NDEBUG_INLINE Output::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Output::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, match_state_),
           0,
           offsetof(Impl_, config_) -
               offsetof(Impl_, match_state_) +
               sizeof(Impl_::config_));
}
Output::~Output() {
  // @@protoc_insertion_point(destructor:Output)
  SharedDtor(*this);
}
inline void Output::SharedDtor(MessageLite& self) {
  Output& this_ = static_cast<Output&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.match_state_;
  delete this_._impl_.gc_state_;
  delete this_._impl_.protocol_;
  delete this_._impl_.config_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Output::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Output(arena);
}
constexpr auto Output::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Output),
                                            alignof(Output));
}
constexpr auto Output::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Output_default_instance_._instance,
          &_table_.header,
          Output::IsInitializedImpl,
          &Output::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Output>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Output::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Output>(), &Output::ByteSizeLong,
              &Output::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Output, _impl_._cached_size_),
          false,
      },
      &Output::kDescriptorMethods,
      &descriptor_table_api_2fssl_5fgc_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Output_class_data_ =
        Output::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Output::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Output_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Output_class_data_.tc_table);
  return Output_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 4, 0, 2>
Output::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Output, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Output_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Output>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .Config config = 4 [json_name = "config"];
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3,
      PROTOBUF_FIELD_OFFSET(Output, _impl_.config_)}},
    // optional .State match_state = 1 [json_name = "matchState"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Output, _impl_.match_state_)}},
    // optional .GcState gc_state = 2 [json_name = "gcState"];
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(Output, _impl_.gc_state_)}},
    // optional .Protocol protocol = 3 [json_name = "protocol"];
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2,
      PROTOBUF_FIELD_OFFSET(Output, _impl_.protocol_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .State match_state = 1 [json_name = "matchState"];
    {PROTOBUF_FIELD_OFFSET(Output, _impl_.match_state_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .GcState gc_state = 2 [json_name = "gcState"];
    {PROTOBUF_FIELD_OFFSET(Output, _impl_.gc_state_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .Protocol protocol = 3 [json_name = "protocol"];
    {PROTOBUF_FIELD_OFFSET(Output, _impl_.protocol_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .Config config = 4 [json_name = "config"];
    {PROTOBUF_FIELD_OFFSET(Output, _impl_.config_), _Internal::kHasBitsOffset + 3, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::State>()},
      {::_pbi::TcParser::GetTable<::GcState>()},
      {::_pbi::TcParser::GetTable<::Protocol>()},
      {::_pbi::TcParser::GetTable<::Config>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Output::Clear() {
// @@protoc_insertion_point(message_clear_start:Output)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.match_state_ != nullptr);
      _impl_.match_state_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.gc_state_ != nullptr);
      _impl_.gc_state_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.protocol_ != nullptr);
      _impl_.protocol_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.config_ != nullptr);
      _impl_.config_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Output::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Output& this_ = static_cast<const Output&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Output::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Output& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Output)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .State match_state = 1 [json_name = "matchState"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.match_state_, this_._impl_.match_state_->GetCachedSize(), target,
        stream);
  }

  // optional .GcState gc_state = 2 [json_name = "gcState"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.gc_state_, this_._impl_.gc_state_->GetCachedSize(), target,
        stream);
  }

  // optional .Protocol protocol = 3 [json_name = "protocol"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.protocol_, this_._impl_.protocol_->GetCachedSize(), target,
        stream);
  }

  // optional .Config config = 4 [json_name = "config"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.config_, this_._impl_.config_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Output)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Output::ByteSizeLong(const MessageLite& base) {
  const Output& this_ = static_cast<const Output&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Output::ByteSizeLong() const {
  const Output& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Output)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // optional .State match_state = 1 [json_name = "matchState"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.match_state_);
    }
    // optional .GcState gc_state = 2 [json_name = "gcState"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.gc_state_);
    }
    // optional .Protocol protocol = 3 [json_name = "protocol"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.protocol_);
    }
    // optional .Config config = 4 [json_name = "config"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.config_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Output::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Output*>(&to_msg);
  auto& from = static_cast<const Output&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Output)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.match_state_ != nullptr);
      if (_this->_impl_.match_state_ == nullptr) {
        _this->_impl_.match_state_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.match_state_);
      } else {
        _this->_impl_.match_state_->MergeFrom(*from._impl_.match_state_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.gc_state_ != nullptr);
      if (_this->_impl_.gc_state_ == nullptr) {
        _this->_impl_.gc_state_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.gc_state_);
      } else {
        _this->_impl_.gc_state_->MergeFrom(*from._impl_.gc_state_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.protocol_ != nullptr);
      if (_this->_impl_.protocol_ == nullptr) {
        _this->_impl_.protocol_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.protocol_);
      } else {
        _this->_impl_.protocol_->MergeFrom(*from._impl_.protocol_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.config_ != nullptr);
      if (_this->_impl_.config_ == nullptr) {
        _this->_impl_.config_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_);
      } else {
        _this->_impl_.config_->MergeFrom(*from._impl_.config_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Output::CopyFrom(const Output& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Output)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Output::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Output&>(msg);
  if (CheckHasBit(this_._impl_._has_bits_[0], 0x00000001U)) {
    if (!this_._impl_.match_state_->IsInitialized()) return false;
  }
  if (CheckHasBit(this_._impl_._has_bits_[0], 0x00000002U)) {
    if (!this_._impl_.gc_state_->IsInitialized()) return false;
  }
  if (CheckHasBit(this_._impl_._has_bits_[0], 0x00000004U)) {
    if (!this_._impl_.protocol_->IsInitialized()) return false;
  }
  return true;
}

void Output::InternalSwap(Output* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Output, _impl_.config_)
      + sizeof(Output::_impl_.config_)
      - PROTOBUF_FIELD_OFFSET(Output, _impl_.match_state_)>(
          reinterpret_cast<char*>(&_impl_.match_state_),
          reinterpret_cast<char*>(&other->_impl_.match_state_));
}

::google::protobuf::Metadata Output::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Protocol::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Protocol>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Protocol, _impl_._has_bits_);
};

Protocol::Protocol(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Protocol_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol)
}
PROTOBUF_NDEBUG_INLINE Protocol::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Protocol& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        entry_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::Protocol,
            PROTOBUF_FIELD_OFFSET(::Protocol, _impl_.entry_)>()
        , from.entry_}
        #else
        entry_ { visibility, arena, from.entry_ }
        #endif
     {}

Protocol::Protocol(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Protocol& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Protocol_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Protocol* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.delta_ = from._impl_.delta_;

  // @@protoc_insertion_point(copy_constructor:Protocol)
}
PROTOBUF_NDEBUG_INLINE Protocol::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        entry_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::Protocol,
            PROTOBUF_FIELD_OFFSET(::Protocol, _impl_.entry_)>()
        }
        #else
        entry_ { visibility, arena }
        #endif
     {}

inline void Protocol::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.delta_ = {};
}
Protocol::~Protocol() {
  // @@protoc_insertion_point(destructor:Protocol)
  SharedDtor(*this);
}
inline void Protocol::SharedDtor(MessageLite& self) {
  Protocol& this_ = static_cast<Protocol&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Protocol::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Protocol(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto Protocol::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Protocol),
                                            alignof(Protocol));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto Protocol::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Protocol, _impl_.entry_) +
          decltype(Protocol::_impl_.entry_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Protocol), alignof(Protocol), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Protocol::PlacementNew_,
                                 sizeof(Protocol),
                                 alignof(Protocol));
  }
}
#endif
constexpr auto Protocol::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Protocol_default_instance_._instance,
          &_table_.header,
          Protocol::IsInitializedImpl,
          &Protocol::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Protocol>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Protocol::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Protocol>(), &Protocol::ByteSizeLong,
              &Protocol::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Protocol, _impl_._cached_size_),
          false,
      },
      &Protocol::kDescriptorMethods,
      &descriptor_table_api_2fssl_5fgc_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Protocol_class_data_ =
        Protocol::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Protocol::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Protocol_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Protocol_class_data_.tc_table);
  return Protocol_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
Protocol::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Protocol, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Protocol_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .ProtocolEntry entry = 2 [json_name = "entry"];
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Protocol, _impl_.entry_)}},
    // optional bool delta = 1 [json_name = "delta"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Protocol, _impl_.delta_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(Protocol, _impl_.delta_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool delta = 1 [json_name = "delta"];
    {PROTOBUF_FIELD_OFFSET(Protocol, _impl_.delta_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // repeated .ProtocolEntry entry = 2 [json_name = "entry"];
    {PROTOBUF_FIELD_OFFSET(Protocol, _impl_.entry_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::ProtocolEntry>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Protocol::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.entry_.Clear();
  }
  _impl_.delta_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Protocol::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Protocol& this_ = static_cast<const Protocol&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Protocol::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Protocol& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bool delta = 1 [json_name = "delta"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_delta(), target);
  }

  // repeated .ProtocolEntry entry = 2 [json_name = "entry"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_entry_size());
         i < n; i++) {
      const auto& repfield = this_._internal_entry().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Protocol::ByteSizeLong(const MessageLite& base) {
  const Protocol& this_ = static_cast<const Protocol&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Protocol::ByteSizeLong() const {
  const Protocol& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000002U & cached_has_bits) * 2;
   {
    // repeated .ProtocolEntry entry = 2 [json_name = "entry"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_entry_size();
      for (const auto& msg : this_._internal_entry()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Protocol::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Protocol*>(&to_msg);
  auto& from = static_cast<const Protocol&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_entry()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_entry());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.delta_ = from._impl_.delta_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Protocol::CopyFrom(const Protocol& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Protocol::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Protocol&>(msg);
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_entry()))
    return false;
  return true;
}

void Protocol::InternalSwap(Protocol* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.entry_.InternalSwap(&other->_impl_.entry_);
  swap(_impl_.delta_, other->_impl_.delta_);
}

::google::protobuf::Metadata Protocol::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtocolEntry::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ProtocolEntry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_._has_bits_);
};

void ProtocolEntry::clear_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ != nullptr) _impl_.change_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
void ProtocolEntry::clear_match_time_elapsed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.match_time_elapsed_ != nullptr) _impl_.match_time_elapsed_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void ProtocolEntry::clear_stage_time_elapsed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.stage_time_elapsed_ != nullptr) _impl_.stage_time_elapsed_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
ProtocolEntry::ProtocolEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProtocolEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ProtocolEntry)
}
PROTOBUF_NDEBUG_INLINE ProtocolEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ProtocolEntry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtocolEntry::ProtocolEntry(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ProtocolEntry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProtocolEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtocolEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.change_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_)
                : nullptr;
  _impl_.match_time_elapsed_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.match_time_elapsed_)
                : nullptr;
  _impl_.stage_time_elapsed_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.stage_time_elapsed_)
                : nullptr;
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:ProtocolEntry)
}
PROTOBUF_NDEBUG_INLINE ProtocolEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ProtocolEntry::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, change_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, change_) +
               sizeof(Impl_::id_));
}
ProtocolEntry::~ProtocolEntry() {
  // @@protoc_insertion_point(destructor:ProtocolEntry)
  SharedDtor(*this);
}
inline void ProtocolEntry::SharedDtor(MessageLite& self) {
  ProtocolEntry& this_ = static_cast<ProtocolEntry&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.change_;
  delete this_._impl_.match_time_elapsed_;
  delete this_._impl_.stage_time_elapsed_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ProtocolEntry::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ProtocolEntry(arena);
}
constexpr auto ProtocolEntry::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ProtocolEntry),
                                            alignof(ProtocolEntry));
}
constexpr auto ProtocolEntry::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ProtocolEntry_default_instance_._instance,
          &_table_.header,
          ProtocolEntry::IsInitializedImpl,
          &ProtocolEntry::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ProtocolEntry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ProtocolEntry::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ProtocolEntry>(), &ProtocolEntry::ByteSizeLong,
              &ProtocolEntry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_._cached_size_),
          false,
      },
      &ProtocolEntry::kDescriptorMethods,
      &descriptor_table_api_2fssl_5fgc_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ProtocolEntry_class_data_ =
        ProtocolEntry::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ProtocolEntry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ProtocolEntry_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ProtocolEntry_class_data_.tc_table);
  return ProtocolEntry_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 3, 0, 2>
ProtocolEntry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ProtocolEntry_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ProtocolEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .google.protobuf.Duration stage_time_elapsed = 4 [json_name = "stageTimeElapsed"];
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 2,
      PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.stage_time_elapsed_)}},
    // optional int32 id = 1 [json_name = "id"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProtocolEntry, _impl_.id_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.id_)}},
    // optional .Change change = 2 [json_name = "change"];
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.change_)}},
    // optional .google.protobuf.Duration match_time_elapsed = 3 [json_name = "matchTimeElapsed"];
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1,
      PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.match_time_elapsed_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 id = 1 [json_name = "id"];
    {PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .Change change = 2 [json_name = "change"];
    {PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.change_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .google.protobuf.Duration match_time_elapsed = 3 [json_name = "matchTimeElapsed"];
    {PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.match_time_elapsed_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .google.protobuf.Duration stage_time_elapsed = 4 [json_name = "stageTimeElapsed"];
    {PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.stage_time_elapsed_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Change>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Duration>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Duration>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ProtocolEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtocolEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.change_ != nullptr);
      _impl_.change_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.match_time_elapsed_ != nullptr);
      _impl_.match_time_elapsed_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.stage_time_elapsed_ != nullptr);
      _impl_.stage_time_elapsed_->Clear();
    }
  }
  _impl_.id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ProtocolEntry::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ProtocolEntry& this_ = static_cast<const ProtocolEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ProtocolEntry::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ProtocolEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ProtocolEntry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 id = 1 [json_name = "id"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_id(), target);
  }

  // optional .Change change = 2 [json_name = "change"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.change_, this_._impl_.change_->GetCachedSize(), target,
        stream);
  }

  // optional .google.protobuf.Duration match_time_elapsed = 3 [json_name = "matchTimeElapsed"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.match_time_elapsed_, this_._impl_.match_time_elapsed_->GetCachedSize(), target,
        stream);
  }

  // optional .google.protobuf.Duration stage_time_elapsed = 4 [json_name = "stageTimeElapsed"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.stage_time_elapsed_, this_._impl_.stage_time_elapsed_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtocolEntry)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ProtocolEntry::ByteSizeLong(const MessageLite& base) {
  const ProtocolEntry& this_ = static_cast<const ProtocolEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ProtocolEntry::ByteSizeLong() const {
  const ProtocolEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ProtocolEntry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // optional .Change change = 2 [json_name = "change"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.change_);
    }
    // optional .google.protobuf.Duration match_time_elapsed = 3 [json_name = "matchTimeElapsed"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.match_time_elapsed_);
    }
    // optional .google.protobuf.Duration stage_time_elapsed = 4 [json_name = "stageTimeElapsed"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.stage_time_elapsed_);
    }
    // optional int32 id = 1 [json_name = "id"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ProtocolEntry::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ProtocolEntry*>(&to_msg);
  auto& from = static_cast<const ProtocolEntry&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:ProtocolEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.change_ != nullptr);
      if (_this->_impl_.change_ == nullptr) {
        _this->_impl_.change_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_);
      } else {
        _this->_impl_.change_->MergeFrom(*from._impl_.change_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.match_time_elapsed_ != nullptr);
      if (_this->_impl_.match_time_elapsed_ == nullptr) {
        _this->_impl_.match_time_elapsed_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.match_time_elapsed_);
      } else {
        _this->_impl_.match_time_elapsed_->MergeFrom(*from._impl_.match_time_elapsed_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.stage_time_elapsed_ != nullptr);
      if (_this->_impl_.stage_time_elapsed_ == nullptr) {
        _this->_impl_.stage_time_elapsed_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.stage_time_elapsed_);
      } else {
        _this->_impl_.stage_time_elapsed_->MergeFrom(*from._impl_.stage_time_elapsed_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.id_ = from._impl_.id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ProtocolEntry::CopyFrom(const ProtocolEntry& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ProtocolEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProtocolEntry::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const ProtocolEntry&>(msg);
  if (CheckHasBit(this_._impl_._has_bits_[0], 0x00000001U)) {
    if (!this_._impl_.change_->IsInitialized()) return false;
  }
  return true;
}

void ProtocolEntry::InternalSwap(ProtocolEntry* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.id_)
      + sizeof(ProtocolEntry::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(ProtocolEntry, _impl_.change_)>(
          reinterpret_cast<char*>(&_impl_.change_),
          reinterpret_cast<char*>(&other->_impl_.change_));
}

::google::protobuf::Metadata ProtocolEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Input::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Input>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Input, _impl_._has_bits_);
};

void Input::clear_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ != nullptr) _impl_.change_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
void Input::clear_config_delta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.config_delta_ != nullptr) _impl_.config_delta_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void Input::clear_continue_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.continue_action_ != nullptr) _impl_.continue_action_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
Input::Input(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Input_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Input)
}
PROTOBUF_NDEBUG_INLINE Input::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Input& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Input::Input(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Input& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Input_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Input* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.change_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_)
                : nullptr;
  _impl_.config_delta_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_delta_)
                : nullptr;
  _impl_.continue_action_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.continue_action_)
                : nullptr;
  _impl_.reset_match_ = from._impl_.reset_match_;

  // @@protoc_insertion_point(copy_constructor:Input)
}
PROTOBUF_NDEBUG_INLINE Input::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Input::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, change_),
           0,
           offsetof(Impl_, reset_match_) -
               offsetof(Impl_, change_) +
               sizeof(Impl_::reset_match_));
}
Input::~Input() {
  // @@protoc_insertion_point(destructor:Input)
  SharedDtor(*this);
}
inline void Input::SharedDtor(MessageLite& self) {
  Input& this_ = static_cast<Input&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.change_;
  delete this_._impl_.config_delta_;
  delete this_._impl_.continue_action_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Input::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Input(arena);
}
constexpr auto Input::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Input),
                                            alignof(Input));
}
constexpr auto Input::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Input_default_instance_._instance,
          &_table_.header,
          Input::IsInitializedImpl,
          &Input::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Input>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Input::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Input>(), &Input::ByteSizeLong,
              &Input::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Input, _impl_._cached_size_),
          false,
      },
      &Input::kDescriptorMethods,
      &descriptor_table_api_2fssl_5fgc_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Input_class_data_ =
        Input::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Input::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Input_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Input_class_data_.tc_table);
  return Input_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 3, 0, 2>
Input::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Input, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Input_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Input>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .ContinueAction continue_action = 4 [json_name = "continueAction"];
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 2,
      PROTOBUF_FIELD_OFFSET(Input, _impl_.continue_action_)}},
    // optional .Change change = 1 [json_name = "change"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Input, _impl_.change_)}},
    // optional bool reset_match = 2 [json_name = "resetMatch"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Input, _impl_.reset_match_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(Input, _impl_.reset_match_)}},
    // optional .Config config_delta = 3 [json_name = "configDelta"];
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1,
      PROTOBUF_FIELD_OFFSET(Input, _impl_.config_delta_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .Change change = 1 [json_name = "change"];
    {PROTOBUF_FIELD_OFFSET(Input, _impl_.change_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bool reset_match = 2 [json_name = "resetMatch"];
    {PROTOBUF_FIELD_OFFSET(Input, _impl_.reset_match_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .Config config_delta = 3 [json_name = "configDelta"];
    {PROTOBUF_FIELD_OFFSET(Input, _impl_.config_delta_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .ContinueAction continue_action = 4 [json_name = "continueAction"];
    {PROTOBUF_FIELD_OFFSET(Input, _impl_.continue_action_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Change>()},
      {::_pbi::TcParser::GetTable<::Config>()},
      {::_pbi::TcParser::GetTable<::ContinueAction>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Input::Clear() {
// @@protoc_insertion_point(message_clear_start:Input)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.change_ != nullptr);
      _impl_.change_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.config_delta_ != nullptr);
      _impl_.config_delta_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.continue_action_ != nullptr);
      _impl_.continue_action_->Clear();
    }
  }
  _impl_.reset_match_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Input::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Input& this_ = static_cast<const Input&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Input::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Input& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Input)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .Change change = 1 [json_name = "change"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.change_, this_._impl_.change_->GetCachedSize(), target,
        stream);
  }

  // optional bool reset_match = 2 [json_name = "resetMatch"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this_._internal_reset_match(), target);
  }

  // optional .Config config_delta = 3 [json_name = "configDelta"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.config_delta_, this_._impl_.config_delta_->GetCachedSize(), target,
        stream);
  }

  // optional .ContinueAction continue_action = 4 [json_name = "continueAction"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.continue_action_, this_._impl_.continue_action_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Input)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Input::ByteSizeLong(const MessageLite& base) {
  const Input& this_ = static_cast<const Input&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Input::ByteSizeLong() const {
  const Input& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Input)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000008U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional .Change change = 1 [json_name = "change"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.change_);
    }
    // optional .Config config_delta = 3 [json_name = "configDelta"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.config_delta_);
    }
    // optional .ContinueAction continue_action = 4 [json_name = "continueAction"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.continue_action_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Input::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Input*>(&to_msg);
  auto& from = static_cast<const Input&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Input)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.change_ != nullptr);
      if (_this->_impl_.change_ == nullptr) {
        _this->_impl_.change_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_);
      } else {
        _this->_impl_.change_->MergeFrom(*from._impl_.change_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.config_delta_ != nullptr);
      if (_this->_impl_.config_delta_ == nullptr) {
        _this->_impl_.config_delta_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_delta_);
      } else {
        _this->_impl_.config_delta_->MergeFrom(*from._impl_.config_delta_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.continue_action_ != nullptr);
      if (_this->_impl_.continue_action_ == nullptr) {
        _this->_impl_.continue_action_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.continue_action_);
      } else {
        _this->_impl_.continue_action_->MergeFrom(*from._impl_.continue_action_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.reset_match_ = from._impl_.reset_match_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Input::CopyFrom(const Input& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Input)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Input::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Input&>(msg);
  if (CheckHasBit(this_._impl_._has_bits_[0], 0x00000001U)) {
    if (!this_._impl_.change_->IsInitialized()) return false;
  }
  if (CheckHasBit(this_._impl_._has_bits_[0], 0x00000004U)) {
    if (!this_._impl_.continue_action_->IsInitialized()) return false;
  }
  return true;
}

void Input::InternalSwap(Input* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Input, _impl_.reset_match_)
      + sizeof(Input::_impl_.reset_match_)
      - PROTOBUF_FIELD_OFFSET(Input, _impl_.change_)>(
          reinterpret_cast<char*>(&_impl_.change_),
          reinterpret_cast<char*>(&other->_impl_.change_));
}

::google::protobuf::Metadata Input::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_api_2fssl_5fgc_5fapi_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
